export const titles = {
  home: 'HOME',
  basicMgmt: '기준정보 관리',
  mes: 'MES',
  pms: 'PMS',
  cnc: 'PMS',
  userAuthMgmt: '사용자 권한 관리',
  _authMgmt: '권한 관리', 
  _userMgmt: '유저 관리', 
  factoryMgmt: '공장 기준정보', 
  customerMgmt: '거래처 관리', 
  _customerMgmt: '거래처 정보 관리', 
  _modelMgmt: '모델 관리', 
  processMgmt: '공정 관리', 
  _processMgmt: '공정 종류 관리', 
  _pauseMgmt: '공정 일시정지 유형 등록', 
  qualityMgmt: '품질 기준정보', 
  _defectMgmt: '공정별 불량유형 등록', 
  deviceMgmt: '주변장치 기준정보', 
  machineMgmt: '기계 기준정보', 
  moldMgmt: '금형 기준정보', 
  toolMgmt: '공구 기준정보', 
  rawMgmt: '원자재 기준정보', 
  subMgmt: '부자재 기준정보', 
  productMgmt: '제품 등록 관리', 
  documentMgmt: '문서 관리', 
  businessMgmt: '영업 관리', 
  _orderReg: '수주 정보 등록', 
  _orderList: '수주 현황', 
  _deliveryReg: '납품 정보 등록', 
  _deliveryList: '납품 현황', 
  pmReg: '생산관리 등록', 
  _opReg: '작업지시서 등록', 
  _opList: '작업지시서 리스트', 
  _opReList: '작업 일보 리스트', 
  _opComList: '작업 완료 리스트', 
  mesRawMgmt: '원자재 관리', 
  _rawReg: '원자재 입고 등록',
  _rawStock: '원자재 재고 현황',
  _rawExportList: '원자재 출고 현황',  
  mesSubMgmt: '부자재 관리', 
  _subReg: '부자재 입고 등록', 
  _subStock: '부자재 재고 현황', 
  _subExportList: '부자재 출고 현황',  
  mesToolMgmt: '공구 관리', 
  _toolReg: '공구 입고 등록', 
  _toolList: '공구 입고 리스트', 
  _toolStock: '공구 재고 현황', 
  mesQualityMgmt: '품질 관리', 
  _defectList: '불량 통계 (자주검사 관리)',
  _midRangeList: '초ㆍ중ㆍ종 검사 리스트', 
  _stdList: '작업 표준서 관리', 
  _changeNoti: '변경점 정보 등록', 
  _changeList: '변경점 정보 리스트', 
  stockMgmt: '재고 관리', 
  _stockList: '재고 현황', 
  _productList: '생산/납품 현황', 
  _productListAdmin: '생산/납품 현황(관리자용)',
  outsourceMgmt: '외주 관리',
  _outsourcingOrder: '외주 발주',
  _outsourcingOrderList: '외주 발주 현황',
  _outsourcingImport: '외주 입고',
  _outsourcingImportList: '외주 입고 현황',
  _outsourcingExport: '외주 출고',
  _outsourcingExportList: '외주 출고 현황',
  kpi: 'KPI',
  _pLeadTime: '제조리드타임(P)', 
  _manHour: '작업공수(C)', 
  _defect: '품질 불량률(Q)', 
  _oLeadTime: '수주/납품 리드타임(D)', 
  _powerUsage: '전력사용량(E)', 
  _uph: 'UPH(P)', 
  _operation: '설비가동률(P)', 
  pmReg_bk: '생산관리', 
  _opReg_bk: '생산 계획 관리(작업지시서 등록)', 
  _opList_bk: '생산 계획 관리(작업지시서 리스트)', 
  _opReList_bk: '금일 작업 일보 관리(작업 일보 리스트)', 
  _opComList_bk: '작업 이력 관리(작업 완료 리스트)', 
  _opDefect_bk: '불량 이력 관리', 
  _midRangeList_bk: '자주 검사 관리(초ㆍ중ㆍ종 검사 리스트)', 
  _changeNoti_bk: '제품 변경점 관리(변경점 정보 등록)', 
  _changeList_bk: '제품 변경점 관리(변경점 정보 리스트)', 
  cncMon: '설비 모니터링', 
  _cncMon: 'CNC 설비 모니터링', 
  cncStats: 'CNC 데이터 통계', 
  _prodStats: '생산량', 
  _errorStats: '에러', 
  _idleStats: '기계 비가동 시간', 
  cncMnt: 'CNC 관리', 
  pressMon: '프레스 모니터링', 
  _pressAnalMon: '프레스 분석 모니터링', 
  _pressStsMon: '프레스 현황 모니터링', 
  pressStats: '프레스 통계 및 분석', 
  _capaStats: '능력', 
  _powerStats: '전력', 
  _workStats: '작업시간', 
  pressMnt: '프레스 관리', 
  _errorDetail: '에러 보기', 
  _paramDetail: '파라미터 보기', 
  _camDetail: '캠 보기', 
  _clutchNBrake: '클러치&브레이크', 
  _repReqReg: '설비 수리 요청 등록', 
  _repReqList: '설비 수리 요청 리스트', 
  _repCompList: '설비 수리 완료 리스트', 
  _repCompListAdmin: '설비 수리 완료 리스트(관리자용)', 
  _problemReg: '설비 문제 유형 등록', 
  _pressDailyInspReg: '프레스 일상점검 등록', 
  _pressDailyInspSts: '프레스 일상점검 일일현황', 
  moldMnt: '금형 관리', 
  _moldMgmt: '금형 타수 관리', 
  _moldRepReqReg: '금형 수리 요청 등록', 
  _moldRepReqList: '금형 수리 요청 리스트', 
  _moldRepCompList: '금형 수리 완료 리스트', 
  _moldRepCompListAdmin: '금형 수리 완료 리스트(관리자용)', 
  _moldProblemReg: '금형 문제 유형 등록', 
  _moldDailyInspReg: '금형 일상정검 등록', 
  _moldDailyInspSts: '금형 일상정검 일일현황', 
}

export const auth = {
  _home: 'ROLE_HOME',
  _authMgmt: 'ROLE_HR_01',
  _userMgmt: 'ROLE_HR_02',
  factoryMgmt: 'ROLE_BASE_11',
  _customerMgmt: 'ROLE_BASE_01',
  _modelMgmt: 'ROLE_BASE_08',
  _processMgmt: 'ROLE_BASE_02',
  _pauseMgmt: 'ROLE_BASE_09',
  _defectMgmt: 'ROLE_BASE_03',
  deviceMgmt: 'ROLE_BASE_12',
  machineMgmt: 'ROLE_BASE_04',
  moldMgmt: 'ROLE_BASE_07',
  toolMgmt: 'ROLE_BASE_14',
  rawMgmt: 'ROLE_BASE_06',
  subMgmt: 'ROLE_BASE_13',
  productMgmt: 'ROLE_BASE_15',
  documentMgmt: 'ROLE_BASE_16',
  _orderReg: 'ROLE_SALES_01',
  _orderList: 'ROLE_SALES_02',
  _deliveryReg: 'ROLE_SALES_03',
  _deliveryList: 'ROLE_SALES_04',
  _opReg: 'ROLE_PROD_01',
  _opList: 'ROLE_PROD_02',
  _opReList: 'ROLE_PROD_08',
  _opComList: 'ROLE_PROD_06',
  _rawReg: 'ROLE_RMAT_01',
  _rawStock: 'ROLE_RMAT_02',
  _rawExportList: 'ROLE_RMAT_03',
  _subReg: 'ROLE_WIP_01',
  _subStock: 'ROLE_WIP_02',
  _subExportList: 'ROLE_WIP_03',
  _toolReg: 'ROLE_TOOL_01',
  _toolList: 'ROLE_TOOL_02',
  _toolStock: 'ROLE_TOOL_03',
  _defectList: 'ROLE_QA_01',
  _midRangeList: 'ROLE_QA_02',
  _stdList: 'ROLE_QA_03',
  _changeNoti: 'ROLE_QA_04',
  _changeList: 'ROLE_QA_05',
  _stockList: 'ROLE_STK_01',
  _productList: 'ROLE_STK_02',
  _productListAdmin: 'ROLE_STK_02',
  _outsourcingOrder: 'ROLE_OUTS_01',
  _outsourcingOrderList: 'ROLE_OUTS_01',
  _outsourcingImport: 'ROLE_OUTS_02',
  _outsourcingImportList: 'ROLE_OUTS_02',
  _outsourcingExport: 'ROLE_OUTS_03',
  _outsourcingExportList: 'ROLE_OUTS_03',
  _pLeadTime: 'ROLE_KPI_01',
  _manHour: 'ROLE_KPI_02',
  _defect: 'ROLE_KPI_03',
  _oLeadTime: 'ROLE_KPI_04',
  _powerUsage: 'ROLE_KPI_05',
  _uph: 'ROLE_KPI_06',
  _operation: 'ROLE_KPI_07',
  _opReg_bk: 'ROLE_PROD_01',
  _opList_bk: 'ROLE_PROD_02',
  _opReList_bk: 'ROLE_PROD_08',
  _opComList_bk: 'ROLE_PROD_06',
  _opDefect_bk: 'ROLE_PROD_02',
  _midRangeList_bk: 'ROLE_QA_02',
  _changeNoti_bk: 'ROLE_QA_04',
  _changeList_bk: 'ROLE_QA_05',
  _cncMon: 'ROLE_CMON_01',
  _cncProdStats: 'ROLE_CSTAT_01',
  _cncErrorStats: 'ROLE_CSTAT_03',
  _cncIdleStats: 'ROLE_CSTAT_05',
  _cncRepReqReg: 'ROLE_CMNGT_05',
  _cncRepReqList: 'ROLE_CMNGT_06',
  _cncRepCompList: 'ROLE_CMNGT_07',
  _cncRepCompListAdmin: 'ROLE_CMNGT_08',
  _cncProblemReg: 'ROLE_CMNGT_09',
  _pressAnalMon: 'ROLE_MON_01',
  _pressStsMon: 'ROLE_MON_02',
  _prodStats: 'ROLE_STAT_01',
  _capaStats: 'ROLE_STAT_02',
  _errorStats: 'ROLE_STAT_03',
  _powerStats: 'ROLE_STAT_04',
  _idleStats: 'ROLE_STAT_05',
  _workStats: 'ROLE_STAT_06',
  _errorDetail: 'ROLE_PMNGT_01',
  _paramDetail: 'ROLE_PMNGT_02',
  _camDetail: 'ROLE_PMNGT_03',
  _clutchNBrake: 'ROLE_PMNGT_04',
  _repReqReg: 'ROLE_PMNGT_05',
  _repReqList: 'ROLE_PMNGT_06',
  _repCompList: 'ROLE_PMNGT_07',
  _repCompListAdmin: 'ROLE_PMNGT_08',
  _problemReg: 'ROLE_PMNGT_09',
  _pressDailyInspReg: 'ROLE_PMNGT_10',
  _pressDailyInspSts: 'ROLE_PMNGT_21',
  _moldMgmt: 'ROLE_MMNGT_01',
  _moldRepReqReg: 'ROLE_MMNGT_02',
  _moldRepReqList: 'ROLE_MMNGT_03',
  _moldRepCompList: 'ROLE_MMNGT_04',
  _moldRepCompListAdmin: 'ROLE_MMNGT_05',
  _moldProblemReg: 'ROLE_MMNGT_06',
  _moldDailyInspReg: 'ROLE_MMNGT_07',
  _moldDailyInspSts: 'ROLE_MMNGT_08',
}

function toMenu(title: string, url: string, subMenu ?: string[]) {
  return {title,url,subMenu}
}

export const BasicTitles = (customTarget?: string) => {
  const basicDefault = {
    userAuthMgmt: toMenu(titles.userAuthMgmt, '', [ '_authMgmt', '_userMgmt' ]),
    _authMgmt: toMenu(titles._authMgmt, '/mes/basic/authority/member'),
    _userMgmt: toMenu(titles._userMgmt, '/mes/basic/user'),

    factoryMgmt: toMenu(titles.factoryMgmt, '/mes/basic/factory'),

    customerMgmt: toMenu(titles.customerMgmt, '/mes/basic/factory', [ '_customerMgmt', '_modelMgmt' ]),
    _customerMgmt: toMenu(titles._customerMgmt, '/mes/basic/customer'),
    _modelMgmt: toMenu(titles._modelMgmt, '/mes/basic/customer/model'),

    processMgmt: toMenu(titles.processMgmt, '', [ '_processMgmt', '_pauseMgmt' ]),
    _processMgmt: toMenu(titles._processMgmt, '/mes/basic/process'),
    _pauseMgmt: toMenu(titles._pauseMgmt, '/mes/basic/register/pause'),

    qualityMgmt: toMenu(titles.qualityMgmt, '', [ '_defectMgmt' ]),
    _defectMgmt: toMenu(titles._defectMgmt, '/mes/basic/register/defect'),

    deviceMgmt: toMenu(titles.deviceMgmt, '/mes/basic/device'),
    machineMgmt: toMenu(titles.machineMgmt, '/mes/basic/machine'),
    moldMgmt: toMenu(titles.moldMgmt, '/mes/basic/moldV1u'),
    toolMgmt: toMenu(titles.toolMgmt, '/mes/basic/tool'),
    rawMgmt: toMenu(titles.rawMgmt, '/mes/basic/rawmaterialV1u'),
    subMgmt: toMenu(titles.subMgmt, '/mes/basic/submaterial'),
    productMgmt: toMenu(titles.productMgmt, '/mes/basic/productV1u'),
    documentMgmt: toMenu(titles.documentMgmt, '/mes/basic/document'),
  }
  switch(customTarget){
    default: return basicDefault
  }
}

export const MesTitles = (customTarget?: string) => {
  const mesDefault = {
    businessMgmt: toMenu(titles.businessMgmt, '',['_orderReg','_orderList','_deliveryReg','_deliveryList']),
    _orderReg: toMenu(titles._orderReg, '/mes/order/register'),
    _orderList: toMenu(titles._orderList,'/mes/order/list'),
    _deliveryReg: toMenu(titles._deliveryReg,'/mes/delivery/register'),
    _deliveryList: toMenu(titles._deliveryList,'/mes/delivery/list'),

    pmReg: toMenu(titles.pmReg,'',['_opReg','_opList','_opReList','_opComList']),
    _opReg: toMenu(titles._opReg,'/mes/operationV1u/register'),
    _opList: toMenu(titles._opList,'/mes/operationV1u/list'),
    _opReList: toMenu(titles._opReList,'/mes/recordV2/list'),
    _opComList: toMenu(titles._opComList,'/mes/finishV2/list'),

    rawMgmt: toMenu(titles.mesRawMgmt, '' , ['_rawReg','_rawStock', '_rawExportList']),
    _rawReg: toMenu(titles._rawReg,'/mes/rawmaterialV1u/input'),
    _rawStock: toMenu(titles._rawStock,'/mes/rawmaterialV1u/stock'),
    _rawExportList: toMenu(titles._rawExportList,'/mes/rawmaterialV1u/export/list'),

    subMgmt: toMenu(titles.mesSubMgmt,'',['_subReg','_subStock', '_subExportList']),
    _subReg: toMenu(titles._subReg,'/mes/submaterialV1u/input'),
    _subStock: toMenu(titles._subStock,'/mes/submaterialV1u/stock'),
    _subExportList: toMenu(titles._subExportList,'/mes/submaterialV1u/export/list'),

    toolMgmt: toMenu(titles.mesToolMgmt,'',['_toolReg','_toolList','_toolStock']),
    _toolReg: toMenu(titles._toolReg,'/mes/tool/register'),
    _toolList: toMenu(titles._toolList,'/mes/tool/warehousinglist'),
    _toolStock: toMenu(titles._toolStock,'/mes/tool/list'),

    qualityMgmt: toMenu(titles.mesQualityMgmt,'',['_defectList','_midRangeList','_stdList','_changeNoti','_changeList']),
    _defectList: toMenu(titles._defectList,'/mes/quality/defect'),
    _midRangeList: toMenu(titles._midRangeList,'/mes/quality/midrange/list'),
    _stdList: toMenu(titles._stdList,'/mes/quality/work/standardlist'),
    _changeNoti: toMenu(titles._changeNoti,'/mes/quality/product/change/register'),
    _changeList: toMenu(titles._changeList,'/mes/quality/product/change/list'),

    stockMgmt: toMenu(titles.stockMgmt,'',['_stockList','_productList','_productListAdmin']),
    _stockList: toMenu(titles._stockList,'/mes/stock/list'),
    _productList: toMenu(titles._productList,'/mes/stock/productlist'),
    _productListAdmin: toMenu(titles._productListAdmin,'/mes/stock/admin'),

    outsourceMgmt: toMenu(titles.outsourceMgmt,'',['_outsourcingOrder', '_outsourcingOrderList', '_outsourcingImport', '_outsourcingImportList','_outsourcingExport','_outsourcingExportList']),
    _outsourcingOrder: toMenu(titles._outsourcingOrder,'/mes/outsourcing/order'),
    _outsourcingOrderList: toMenu(titles._outsourcingOrderList,'/mes/outsourcing/order/list'),
    _outsourcingImport: toMenu(titles._outsourcingImport,'/mes/outsourcing/receive'),
    _outsourcingImportList: toMenu(titles._outsourcingImportList,'/mes/outsourcing/receive/list'),
    _outsourcingExport: toMenu(titles._outsourcingExport,'/mes/outsourcing/delivery'),
    _outsourcingExportList: toMenu(titles._outsourcingExportList,'/mes/outsourcing/delivery/list'),

    kpi: toMenu(titles.kpi,'',['_pLeadTime','_manHour','_defect','_oLeadTime','_powerUsage','_uph','_operation']),
    _pLeadTime: toMenu(titles._pLeadTime,'/mes/kpi/leadtime/manufacture'),
    _manHour: toMenu(titles._manHour,'/mes/kpi/manhour'),
    _defect: toMenu(titles._defect,'/mes/kpi/defect'),
    _oLeadTime: toMenu(titles._oLeadTime,'/mes/kpi/leadtime/order'),
    _powerUsage: toMenu(titles._powerUsage,'/mes/kpi/powerusage'),
    _uph: toMenu(titles._uph,'/mes/kpi/uph'),
    _operation: toMenu(titles._operation,'/mes/kpi/operation')
  }
  switch(customTarget){
    case 'bk': return {
      ...mesDefault,
      pmReg: toMenu(titles.pmReg_bk,'',['_opReg','_opList','_opReList','_opComList','_opDefect']),
      _opReg: toMenu(titles._opReg_bk,'/mes/operationV1u/register'),
      _opList: toMenu(titles._opList_bk,'/mes/operationV1u/list'),
      _opReList: toMenu(titles._opReList_bk,'/mes/recordV2/list'),
      _opComList: toMenu(titles._opComList_bk,'/mes/finishV2/list'),
      _opDefect: toMenu(titles._opDefect_bk,'/mes/defect/list'),

      _midRangeList: toMenu(titles._midRangeList_bk,'/mes/quality/midrange/list'),
      _changeNoti: toMenu(titles._changeNoti_bk,'/mes/quality/product/change/register'),
      _changeList: toMenu(titles._changeList_bk,'/mes/quality/product/change/list'),
    }
    default: return mesDefault
  }
}

export const CncTitles = (customTarget?: string) => {
  const cncDefault = {
    cncMon: toMenu(titles.cncMon, '', [ '_cncMon' ]),
    _cncMon: toMenu(titles._cncMon, '/pms/v2/factoryMonitoring'),
    cncStats: toMenu(titles.cncStats, '',['_prodStats', '_errorStats', '_idleStats']),
    _prodStats: toMenu(titles._prodStats, '/pms/v2/analysis/output'),
    _errorStats: toMenu(titles._errorStats, '/pms/v2/analysis/error'),
    _idleStats: toMenu(titles._idleStats, '/pms/v2/analysis/idleTime'),
    cncMnt: toMenu(titles.cncMnt, '', ['_repReqReg', '_repReqList', '_repCompList','_repCompListAdmin', '_problemReg']),
    _repReqReg: toMenu(titles._repReqReg, '/pms/v2/press/maintenance/facilities'),
    _repReqList: toMenu(titles._repReqList, '/pms/v2/press/maintenance/list'),
    _repCompList: toMenu(titles._repCompList, '/pms/v2/press/maintenance/complete'),
    _repCompListAdmin: toMenu(titles._repCompListAdmin, '/pms/v2/press/maintenance/complete/admin'),
    _problemReg: toMenu(titles._problemReg, '/pms/v2/press/maintenance/problem'),
  }
  switch(customTarget){
    default: return cncDefault
  }
}

export const PmsTitles = (customTarget?: string) => {
  const pmsDefault = {
    pressMon: toMenu(titles.pressMon, '', [ '_pressAnalMon', '_pressStsMon' ]),
    _pressAnalMon: toMenu(titles._pressAnalMon, '/pms/v2/factoryMonitoring'),
    _pressStsMon: toMenu(titles._pressStsMon, '/pms/new/monitoring/press'),
    pressStats: toMenu(titles.pressStats, '', [ '_prodStats', '_capaStats', '_errorStats', '_powerStats', '_idleStats', '_workStats' ]),
    _prodStats: toMenu(titles._prodStats, '/pms/v2/analysis/output'),
    _capaStats: toMenu(titles._capaStats, '/pms/v2/analysis/ability'),
    _errorStats: toMenu(titles._errorStats, '/pms/v2/analysis/error'),
    _powerStats: toMenu(titles._powerStats,'/pms/v2/analysis/power'),
    _idleStats: toMenu(titles._idleStats, '/pms/v2/analysis/idleTime'),
    _workStats: toMenu(titles._workStats, '/pms/v2/analysis/workTime'),
    pressMnt: toMenu(titles.pressMnt, '', [ '_errorDetail', '_paramDetail', '_camDetail', '_clutchNBrake', '_repReqReg', '_repReqList', '_repCompList', '_repCompListAdmin', '_problemReg', '_pressDailyInspReg', '_pressDailyInspSts' ]),
    _errorDetail: toMenu(titles._errorDetail, '/pms/v2/press/maintenance/errorview'),
    _paramDetail: toMenu(titles._paramDetail, '/pms/v2/press/maintenance/parameterview'),
    _camDetail: toMenu(titles._camDetail, '/pms/v2/press/maintenance/camview'),
    _clutchNBrake: toMenu(titles._clutchNBrake, '/pms/v2/press/maintenance/clutchandbrake'),
    _repReqReg: toMenu(titles._repReqReg, '/pms/v2/press/maintenance/facilities'),
    _repReqList: toMenu(titles._repReqList, '/pms/v2/press/maintenance/list'),
    _repCompList: toMenu(titles._repCompList, '/pms/v2/press/maintenance/complete'),
    _repCompListAdmin: toMenu(titles._repCompListAdmin, '/pms/v2/press/maintenance/complete/admin'),
    _problemReg: toMenu(titles._problemReg, '/pms/v2/press/maintenance/problem'),
    _pressDailyInspReg: toMenu(titles._pressDailyInspReg, '/pms/v2/press/maintenance/PressDailyRegister'),
    _pressDailyInspSts: toMenu(titles._pressDailyInspSts, '/pms/v2/press/maintenance/PressDailyStatus'),
    moldMnt: toMenu(titles.moldMnt, '', [ '_moldMgmt', '_moldMgmt','_moldRepReqReg','_moldRepReqList','_moldRepCompList','_moldRepCompListAdmin','_moldProblemReg','_moldDailyInspReg','_moldDailyInspSts']),
    _moldMgmt: toMenu(titles._moldMgmt, '/pms/v2/mold/maintenance'),
    _moldRepReqReg: toMenu(titles._moldRepReqReg, '/pms/v2/mold/maintenance/repairs'),
    _moldRepReqList: toMenu(titles._moldRepReqList, '/pms/v2/mold/maintenance/list'),
    _moldRepCompList: toMenu(titles._moldRepCompList, '/pms/v2/mold/maintenance/complete'),
    _moldRepCompListAdmin: toMenu(titles._moldRepCompListAdmin, '/pms/v2/mold/maintenance/complete/admin'),
    _moldProblemReg: toMenu(titles._moldProblemReg, '/pms/v2/mold/maintenance/problem'),
    _moldDailyInspReg: toMenu(titles._moldDailyInspReg, '/pms/v2/press/maintenance/moldDailyRegister'),
    _moldDailyInspSts: toMenu(titles._moldDailyInspSts, '/pms/v2/press/maintenance/moldDailyStatus'),
  }
  switch (customTarget) {
    default:
      return pmsDefault
  }
}

export const toAuth = (title: string, show: boolean, checkable: boolean, check: boolean, child:any[], value?: string) => {
  return {title,show,checkable,check,child,value}
}

export const HomeAuth = (customTarget?: string) => {
  const homeDefault = {
    home: toAuth(titles.home, false, false, true, [], auth._home ),
  }
  switch(customTarget){
    default: return homeDefault
  }
}

  export const BasicAuth = (customTarget?: string) => {
  const basicDefault = {
    userAuthMgmt: toAuth(titles.userAuthMgmt, false,true,false, [ '_authMgmt', '_userMgmt' ]),
    _authMgmt: toAuth(titles._authMgmt, false, true, false, [], auth._authMgmt ),
    _userMgmt: toAuth(titles._userMgmt, false, true, false, [], auth._userMgmt ),
    factoryMgmt: toAuth(titles.factoryMgmt, false, true, false, [], auth.factoryMgmt ),
    customerMgmt: toAuth(titles.customerMgmt, false, true, false, ['_customerMgmt', '_modelMgmt'] ),
    _customerMgmt: toAuth(titles._customerMgmt, false, true, false, [], auth._customerMgmt ),
    _modelMgmt: toAuth(titles._modelMgmt, false, true, false, [], auth._modelMgmt ),
    processMgmt: toAuth(titles.processMgmt, false, true, false, ['_processMgmt', '_pauseMgmt'] ),
    _processMgmt: toAuth(titles._processMgmt, false, true, false, [], auth._processMgmt ),
    _pauseMgmt: toAuth(titles._pauseMgmt, false, true, false, [], auth._pauseMgmt ),
    qualityMgmt: toAuth(titles.qualityMgmt, false, true, false, ['_defectMgmt'] ),
    _defectMgmt: toAuth(titles._defectMgmt, false, true, false, [], auth._defectMgmt ),
    deviceMgmt: toAuth(titles.deviceMgmt, false, true, false, [], auth.deviceMgmt ),
    machineMgmt: toAuth(titles.machineMgmt, false, true, false, [], auth.machineMgmt ),
    moldMgmt: toAuth(titles.moldMgmt, false, true, false, [], auth.moldMgmt ),
    toolMgmt: toAuth(titles.toolMgmt, false, true, false, [], auth.toolMgmt ),
    rawMgmt: toAuth(titles.rawMgmt, false, true, false, [], auth.rawMgmt ),
    subMgmt: toAuth(titles.subMgmt, false, true, false, [], auth.subMgmt ),
    productMgmt: toAuth(titles.productMgmt, false, true, false, [], auth.productMgmt ),
    documentMgmt: toAuth(titles.documentMgmt, false, true, false, [], auth.documentMgmt ),
  }
  switch(customTarget){
    default: return basicDefault
  }
}

export const MesAuth = (customTarget?: string) => {
  const mesDefault = {
    businessMgmt: toAuth(titles.businessMgmt, false, true, false, ['_orderReg', '_orderList','_deliveryReg','_deliveryList']),
    _orderReg: toAuth(titles._orderReg, false, true, false, [], auth._orderReg),
    _orderList: toAuth(titles._orderList, false, true, false, [], auth._orderList),
    _deliveryReg: toAuth(titles._deliveryReg, false, true, false, [], auth._deliveryReg),
    _deliveryList: toAuth(titles._deliveryList, false, true, false, [], auth._deliveryList),
    pmReg: toAuth(titles.pmReg, false, true, false, ['_opReg','_opList','_opReList','_opComList'] ),
    _opReg: toAuth(titles._opReg, false, true, false, [], auth._opReg),
    _opList: toAuth(titles._opList, false, true, false, [], auth._opList),
    _opReList: toAuth(titles._opReList, false, true, false, [], auth._opReList),
    _opComList: toAuth(titles._opComList, false, true, false, [], auth._opComList),
    rawMgmt: toAuth(titles.mesRawMgmt, false, true, false, ['_rawReg','_rawStock','_rawExportList']),
    _rawReg: toAuth(titles._rawReg, false, true, false, [], auth._rawReg),
    _rawStock: toAuth(titles._rawStock, false, true, false, [], auth._rawStock),
    _rawExportList: toAuth(titles._rawExportList, false, true, false, [], auth._rawExportList),
    subMgmt: toAuth(titles.mesSubMgmt, false, true, false, ['_subReg','_subStock','_subExportList']),
    _subReg: toAuth(titles._subReg, false, true, false, [], auth._subReg),
    _subStock: toAuth(titles._subStock, false, true, false, [], auth._subStock),
    _subExportList: toAuth(titles._subExportList, false, true, false, [], auth._subExportList),
    toolMgmt: toAuth(titles.mesToolMgmt, false, true, false, ['_toolReg','_toolList','_toolStock']),
    _toolReg: toAuth(titles._toolReg, false, true, false, [], auth._toolReg),
    _toolList: toAuth(titles._toolList, false, true, false, [], auth._toolList),
    _toolStock: toAuth(titles._toolStock, false, true, false, [], auth._toolStock),
    qualityMgmt: toAuth(titles.mesQualityMgmt, false, true, false, ['_defectList','_midRangeList','_stdList','_changeNoti','_changeList']),
    _defectList: toAuth(titles._defectList, false, true, false, [], auth._defectList),
    _midRangeList: toAuth(titles._midRangeList, false, true, false, [], auth._midRangeList),
    _stdList: toAuth(titles._stdList, false, true, false, [], auth._stdList),
    _changeNoti: toAuth(titles._changeNoti, false, true, false, [], auth._changeNoti),
    _changeList: toAuth(titles._changeList, false, true, false, [], auth._changeList),
    stockMgmt: toAuth(titles.stockMgmt, false, true, false, ['_stockList','_productList','_productListAdmin']),
    _stockList: toAuth(titles._stockList, false, true, false, [], auth._stockList),
    _productList: toAuth(titles._productList, false, true, false, [], auth._productList),
    _productListAdmin: toAuth(titles._productListAdmin, false, true, false, [], auth._productListAdmin),
   outsourceMgmt: toAuth(titles.outsourceMgmt, false, true, false,['_outsourcingOrder', '_outsourcingOrderList', '_outsourcingImport', '_outsourcingImportList','_outsourcingExport','_outsourcingExportList']),
   _outsourcingOrder: toAuth(titles._outsourcingOrder,false, true, false, [], auth._outsourcingOrder),
   _outsourcingOrderList: toAuth(titles._outsourcingOrderList,false, true, false, [], auth._outsourcingOrderList),
   _outsourcingImport: toAuth(titles._outsourcingImport,false, true, false, [], auth._outsourcingImport),
   _outsourcingImportList: toAuth(titles._outsourcingImportList,false, true, false, [], auth._outsourcingImportList),
   _outsourcingExport: toAuth(titles._outsourcingExport,false, true, false, [], auth._outsourcingExport),
   _outsourcingExportList: toAuth(titles._outsourcingExportList,false, true, false, [], auth._outsourcingExportList),
    kpi: toAuth(titles.kpi, false, true, false, ['_pLeadTime','_manHour','_defect','_oLeadTime','_powerUsage','_uph','_operation']),
    _pLeadTime: toAuth(titles._pLeadTime, false, true, false, [], auth._pLeadTime),
    _manHour: toAuth(titles._manHour, false, true, false, [], auth._manHour),
    _defect: toAuth(titles._defect, false, true, false, [], auth._defect),
    _oLeadTime: toAuth(titles._oLeadTime, false, true, false, [], auth._oLeadTime),
    _powerUsage: toAuth(titles._powerUsage, false, true, false, [], auth._powerUsage),
    _uph: toAuth(titles._uph, false, true, false, [], auth._uph),
    _operation: toAuth(titles._operation, false, true, false, [], auth._operation),
  }
  switch(customTarget){
    case 'bk': return {
      ...mesDefault,
      pmReg: toAuth(titles.pmReg_bk, false, true, false, ['_opReg','_opList','_opReList','_opComList','_opDefect'] ),
      _opReg: toAuth(titles._opReg_bk, false, true, false, [], auth._opReg_bk),
      _opList: toAuth(titles._opList_bk, false, true, false, [], auth._opList_bk),
      _opReList: toAuth(titles._opReList_bk, false, true, false, [], auth._opReList_bk),
      _opComList: toAuth(titles._opComList_bk, false, true, false, [], auth._opComList_bk),
      _opDefect: toAuth(titles._opDefect_bk, false, true, false, [], auth._opList_bk),

      _midRangeList: toAuth(titles._midRangeList_bk, false, true, false, [], auth._midRangeList_bk),
      _changeNoti: toAuth(titles._changeNoti_bk, false, true, false, [], auth._changeNoti_bk),
      _changeList: toAuth(titles._changeList_bk, false, true, false, [], auth._changeList_bk),
    }
    default: return mesDefault
  }
}

export const CncAuth = (customTarget?: string) => {
  const cncDefault = {
    cncMon: toAuth(titles.cncMon, false, true, false, ['_cncMon']),
    _cncMon: toAuth(titles._cncMon, false, true, false, [], auth._cncMon),
    cncStats: toAuth(titles.cncStats, false, true, false, ['_prodStats','_errorStats','_idleStats']),
    _prodStats: toAuth(titles._prodStats, false, true, false, [], auth._cncProdStats),
    _errorStats: toAuth(titles._errorStats, false, true, false, [], auth._cncErrorStats),
    _idleStats: toAuth(titles._idleStats, false, true, false, [], auth._cncIdleStats),
    cncMnt: toAuth(titles.cncMnt, false, true, false, ['_repReqReg','_repReqList','_repCompList']),
    _repReqReg: toAuth(titles._repReqReg, false, true, false, [], auth._cncRepReqReg),
    _repReqList: toAuth(titles._repReqList, false, true, false, [], auth._cncRepReqList),
    _repCompList: toAuth(titles._repCompList, false, true, false, [], auth._cncRepCompList),
    _repCompListAdmin: toAuth(titles._repCompListAdmin, false, true, false, [], auth._cncRepCompListAdmin),
    _problemReg: toAuth(titles._problemReg, false, true, false, [], auth._cncProblemReg),
  }
  switch(customTarget){
    default: return cncDefault
  }
}

export const PmsAuth = (customTarget?: string) => {
  const pmsDefault = {
    pressMon: toAuth(titles.pressMon, false, true, false, ['_pressAnalMon','_pressStsMon']),
    _pressAnalMon: toAuth(titles._pressAnalMon, false, true, false, [], auth._pressAnalMon),
    _pressStsMon: toAuth(titles._pressStsMon, false, true, false, [], auth._pressStsMon),
    pressStats: toAuth(titles.pressStats, false, true, false, ['_prodStats','_capaStats','_errorStats','_powerStats','_idleStats','_workStats']),
    _prodStats: toAuth(titles._prodStats, false, true, false, [], auth._prodStats),
    _capaStats: toAuth(titles._capaStats, false, true, false, [], auth._capaStats),
    _errorStats: toAuth(titles._errorStats, false, true, false, [], auth._errorStats),
    _powerStats: toAuth(titles._powerStats, false, true, false, [], auth._powerStats),
    _idleStats: toAuth(titles._idleStats, false, true, false, [], auth._idleStats),
    _workStats: toAuth(titles._workStats, false, true, false, [], auth._workStats),
    pressMnt: toAuth(titles.pressMnt, false, true, false, ['_errorDetail','_paramDetail','_camDetail','_clutchNBrake','_repReqReg','_repReqList','_repCompList','_repCompListAdmin','_problemReg','_pressDailyInspReg','_pressDailyInspSts']),
    _errorDetail: toAuth(titles._errorDetail, false, true, false, [], auth._errorDetail),
    _paramDetail: toAuth(titles._paramDetail, false, true, false, [], auth._paramDetail),
    _camDetail: toAuth(titles._camDetail, false, true, false, [], auth._camDetail),
    _clutchNBrake: toAuth(titles._clutchNBrake, false, true, false, [], auth._clutchNBrake),
    _repReqReg: toAuth(titles._repReqReg, false, true, false, [], auth._repReqReg),
    _repReqList: toAuth(titles._repReqList, false, true, false, [], auth._repReqList),
    _repCompList: toAuth(titles._repCompList, false, true, false, [], auth._repCompList),
    _repCompListAdmin: toAuth(titles._repCompListAdmin, false, true, false, [], auth._repCompListAdmin),
    _problemReg: toAuth(titles._problemReg, false, true, false, [], auth._problemReg),
    _pressDailyInspReg: toAuth(titles._pressDailyInspReg, false, true, false, [], auth._pressDailyInspReg),
    _pressDailyInspSts: toAuth(titles._pressDailyInspSts, false, true, false, [], auth._pressDailyInspSts),
    moldMnt: toAuth(titles.moldMnt, false, true, false, ['_moldMgmt','_moldRepReqReg','_moldRepReqList','_moldRepCompList','_moldRepCompListAdmin','_moldProblemReg','_moldDailyInspReg','_moldDailyInspSts']),
    _moldMgmt: toAuth(titles._moldMgmt, false, true, false, [], auth._moldMgmt),
    _moldRepReqReg: toAuth(titles._moldRepReqReg, false, true, false, [], auth._moldRepReqReg),
    _moldRepReqList: toAuth(titles._moldRepReqList, false, true, false, [], auth._moldRepReqList),
    _moldRepCompList: toAuth(titles._moldRepCompList, false, true, false, [], auth._moldRepCompList),
    _moldRepCompListAdmin: toAuth(titles._moldRepCompListAdmin, false, true, false, [], auth._moldRepCompListAdmin),
    _moldProblemReg: toAuth(titles._moldProblemReg, false, true, false, [], auth._moldProblemReg),
    _moldDailyInspReg: toAuth(titles._moldDailyInspReg, false, true, false, [], auth._moldDailyInspReg),
    _moldDailyInspSts: toAuth(titles._moldDailyInspSts, false, true, false, [], auth._moldDailyInspSts),
  }
  switch (customTarget) {
    default:
      return pmsDefault
  }
}