export const titles = {
    home: 'HOME',
    basicMgmt: '기준정보 관리',
    mes: 'MES',
    pms: 'PMS',
    cnc: 'CNC',
    userAuthMgmt: '사용자 권한 관리',
    _authMgmt: '권한 관리',
    _userMgmt: '유저 관리',
    factoryMgmt: '공장 기준정보',
    customerMgmt: '거래처 관리',
    _customerMgmt: '거래처 정보 관리',
    _modelMgmt: '모델 관리',
    processMgmt: '공정 관리',
    _processMgmt: '공정 종류 관리',
    _pauseMgmt: '공정 일시정지 유형 등록',
    qualityMgmt: '품질 기준정보',
    _defectMgmt: '공정별 불량유형 등록',
    deviceMgmt: '주변장치 기준정보',
    machineMgmt: '기계 기준정보',
    moldMgmt: '금형 기준정보',
    toolMgmt: '공구 기준정보',
    rawMgmt: '원자재 기준정보',
    subMgmt: '부자재 기준정보',
    productMgmt: '제품 등록 관리',
    documentMgmt: '문서 관리',
    businessMgmt: '영업 관리',
    _orderReg: '수주 정보 등록',
    _orderList: '수주 현황',
    _deliveryReg: '납품 정보 등록',
    _deliveryList: '납품 현황',
    pmReg: '생산관리 등록',
    _opReg: '작업지시서 등록',
    _opList: '작업지시서 리스트',
    _opReList: '작업 일보 리스트',
    _opComList: '작업 완료 리스트',
    mesRawMgmt: '원자재 관리',
    _rawReg: '원자재 입고 등록',
    _rawStock: '원자재 재고 현황',
    _rawExportList: '원자재 출고 현황',
    mesSubMgmt: '부자재 관리',
    _subReg: '부자재 입고 등록',
    _subStock: '부자재 재고 현황',
    _subExportList: '부자재 출고 현황',
    mesToolMgmt: '공구 관리',
    _toolReg: '공구 입고 등록',
    _toolList: '공구 입고 리스트',
    _toolStock: '공구 재고 현황',
    mesQualityMgmt: '품질 관리',
    _defectList: '불량 통계 (자주검사 관리)',
    _midRangeList: '초ㆍ중ㆍ종 검사 리스트',
    _stdList: '작업 표준서 관리',
    _changeNoti: '변경점 정보 등록',
    _changeList: '변경점 정보 리스트',
    stockMgmt: '재고 관리',
    _stockList: '재고 현황',
    _productList: '생산/납품 현황',
    _productListAdmin: '생산/납품 현황(관리자용)',
    outsourceMgmt: '외주 관리',
    _outsourcingOrder: '외주 발주 등록',
    _outsourcingOrderList: '외주 발주 현황',
    _outsourcingImport: '외주 입고 등록',
    _outsourcingImportList: '외주 입고 현황',
    _outsourcingExport: '외주 출고 등록',
    _outsourcingExportList: '외주 출고 현황',
    kpi: 'KPI',
    _pLeadTime: '제조리드타임(P)',
    _manHour: '작업공수(C)',
    _defect: '품질 불량률(Q)',
    _oLeadTime: '수주/납품 리드타임(D)',
    _powerUsage: '전력사용량(E)',
    _uph: 'UPH(P)',
    _operation: '설비가동률(P)',
    cncMon: '설비 모니터링',
    _cncMon: 'CNC 설비 모니터링',
    cncStats: 'CNC 데이터 통계',
    _prodStats: '생산량',
    _errorStats: '에러',
    _idleStats: '기계 비 가동시간',
    cncMnt: 'CNC 관리',
    pressMon: '프레스 모니터링',
    _pressAnalMon: '프레스 분석 모니터링',
    _pressStsMon: '프레스 현황 모니터링',
    pressStats: '프레스 통계 및 분석',
    _capaStats: '능력',
    _powerStats: '전력',
    _workStats: '작업시간',
    pressMnt: '프레스 관리',
    _errorDetail: '에러 보기',
    _paramDetail: '파라미터 보기',
    _camDetail: '캠 보기',
    _clutchNBrake: '클러치&브레이크',
    _repReqReg: '설비 수리 요청 등록',
    _repReqList: '설비 수리 요청 리스트',
    _repCompList: '설비 수리 완료 리스트',
    _repCompListAdmin: '설비 수리 완료 리스트(관리자용)',
    _problemReg: '설비 문제 유형 등록',
    _pressDailyInspReg: '프레스 일상점검 등록',
    _pressDailyInspSts: '프레스 일상점검 일일현황',
    moldMnt: '금형 관리',
    _moldMgmt: '금형 타수 관리',
    _moldRepReqReg: '금형 수리 요청 등록',
    _moldRepReqList: '금형 수리 요청 리스트',
    _moldRepCompList: '금형 수리 완료 리스트',
    _moldRepCompListAdmin: '금형 수리 완료 리스트(관리자용)',
    _moldProblemReg: '금형 문제 유형 등록',
    _moldDailyInspReg: '금형 일상정검 등록',
    _moldDailyInspSts: '금형 일상정검 일일현황',
}

export const dohwaTitles = {
    _modelMgmt: '거래처 모델 관리',
    documentMgmt: '표준 문서 관리',
    _orderReg: '수주 관리(등록)',
    _orderList: '수주 리스트',
    _deliveryReg: '납품 관리(등록)',
    _deliveryList: '납품 리스트',
    _stdList: '작업 표준서 리스트',
    _changeNoti: '제품 변경점 등록',
    _changeList: '제품 변경점 리스트',
    _pauseMgmt: '일시정지 유형 등록',
    pmReg: '생산 관리',
    cncMon: '설비 모니터링 시스템',
    _cncMon: '설비 모니터링',
    _repCompListAdmin: '설비 수리 완료 리스트(관리자)',
}

export const bkTitles = {
    pmReg: '생산관리',
    _opReg: '생산 계획 관리(작업지시서 등록)',
    _opList: '생산 계획 관리(작업지시서 리스트)',
    _opReList: '금일 작업 일보 관리(작업 일보 리스트)',
    _opComList: '작업 이력 관리(작업 완료 리스트)',
    _opDefect: '불량 이력 관리',
    _midRangeList: '자주 검사 관리(초ㆍ중ㆍ종 검사 리스트)',
    _changeNoti: '제품 변경점 관리(변경점 정보 등록)',
    _changeList: '제품 변경점 관리(변경점 정보 리스트)',
}


