export const alertMsg = {
  noData: "데이터를 입력해주세요.",
  noSelectedData: '선택된 정보가 없습니다.',
  noFirstDelete: '첫번째 행은 삭제할 수 없습니다.',
  noBom: 'BOM 정보가 없습니다.',
  needsBom: '투입자재를 선택해 주세요.',
  noLotNumber: 'LOT번호를 입력해 주세요.',
  noWorker: '작업자를 선택해 주세요.',
  noImporter: '입고자를 선택해 주세요.',
  noProduct: '제품을 선택해 주세요.',
  noRawMaterial: '원자재를 선택해 주세요.',
  noSubMaterial: '부자재를 선택해 주세요.',
  noTool: '공구를 선택해 주세요.',
  noOutOrder: '발주 내역을 선택해 주세요.',
  noProductAmount: '생산 수량을 입력해 주세요.',
  noImportAmount: '입고량을 입력해 주세요.',
  noOrderAmount: '발주량을 입력해 주세요.',
  productAmountNotCavityDivisor: '생산 수량을 다시 입력해 주세요.(Lot별 생산량은 캐비티의 배수여야 합니다.)',
  updateProductAmount: '생산 수량을 다시 입력해 주세요.',
  overStock: '재고가 부족합니다.',
  onlyInteger: '정수로 입력해 주세요.',
  wrongLotNumber: 'LOT번호를 다시 입력해 주세요.(\'basicstock-(숫자)\' 또는 \'adjuststock-(숫자)\'는 불가합니다.)',
  overImport: '입고량이 미입고량 보다 클 수 없습니다.',
  onlyOne: '데이터를 하나만 선택해 주세요',
  exportedNotUpdatable: '출고된 정보는 수정할 수 없습니다.',
  importedNotUpdatable: '입고된 정보는 수정할 수 없습니다.',
  duplicateLotNumber:'LOT번호는 중복될 수 없습니다.',
  noOperation:'지시 고유 번호를 선택해주세요.',
  duplicateCode:'중복된 CODE 입니다.'
}
