import {TextEditor} from '../components/InputBox/ExcelBasicInputBox'
import {DropDownEditor} from '../components/Dropdown/ExcelBasicDropdown'
import {CalendarBox} from '../components/CalendarBox/CalendarBox'
import {CellButtonComponent} from '../components/Buttons/CellButtom'
import {UnitContainer} from '../components/Unit/UnitContainer'
import {MoveButtons} from "../components/MoveButtons";
import {FileEditer} from '../components/FileUpload/ExcelBasicFileUpload'
import {TitleFileUpload} from '../components/FileUpload/TitleFileUpload'
import {MemberSearchModal} from '../components/Modal/MemeberSearchModal'
import {ProductSearchModal} from '../components/Modal/ProductSearchModal'
import {CustomerSearchModal} from '../components/Modal/CustomerSearchModal'
import {ModelSearchModal} from '../components/Modal/ModelSearchModal'
import {MachineSearchModal} from '../components/Modal/MachineSearchModal'
import {RawMaterialSearchModal} from '../components/Modal/RawMaterialSearchModal'
import {OperationSearchModal} from '../components/Modal/OperationSearchModal'
import {PoorQuantityModal} from '../components/Modal/PoorQuantityModal'
import {DatetimePickerBox} from '../components/CalendarBox/DatetimePickerBox'
import {ProcessSearchModal} from '../components/Modal/ProcessSearchModal'
import {ProcessSeqModal} from '../components/Modal/ProcessSeqModal'
import {HeaderFilter} from "../components/HeaderFilter/HeaderFilter";
import {PauseModal} from '../components/Modal/PauseModal'
import {AuthoritySearchModal} from '../components/Modal/AuthoritySearchModal'
import {RecordDetailFormatter} from '../components/Formatter/RecordDetailFormatter'
import {OperationMachineSearchModal} from "../components/Modal/OperationMachineSearchModal";
// @ts-ignore
import {StatusComponent} from '../components/Formatter/StatusComponent'
import {MultipleSelectModal} from "../components/Modal/MultipleSelectModal";
import {FactoryInfoModal} from '../components/Modal/FactoryInfoModal'
import {DeviceInfoModal} from '../components/Modal/DeviceInfoModal'
import {PlaceholderBox} from '../components/Formatter/PlaceholderBox'
import {ProductInfoModal} from '../components/Modal/ProductInfoModal'
import {MoldInfoModal} from '../components/Modal/MoldInfoModal'
import {MachineInfoModal} from '../components/Modal/MachineInfoModal'
import {BomInfoModal} from '../components/Modal/BomInfoModal'
import {UseDateCell} from '../components/Cell/UseDateCell'
import {InfoModal} from '../components/Modal/InfoModal'
import {BomRegisterInit} from '../components/Modal/InfoModal/InfoModalInit'
import {BomRegisterModal} from '../components/Modal/BomRegisterModal'
import {InputMaterialInfoModal} from '../components/Modal/InputMaterialInfoModal'
import {WorkRegisterModal} from '../components/Modal/WorkRegisterModal'
import {WorkListModal} from '../components/Modal/WorkListModal'
import {MoldListModal} from '../components/Modal/MoldListModal'
import {MachineListModal} from '../components/Modal/MachineListModal'
import {DefectInfoModal} from '../components/Modal/DefectInfoModal'
import {SearchModalTest} from '../components/Modal/SearchModalTest'
import {LotInfoModal} from '../components/Modal/LotInfoModal'
import {OperationInfoModal} from '../components/Modal/OperationInfoModal'
import {DeliveryInfoModal} from '../components/Modal/DeliveryInfoModal'
import {FinishButton} from '../components/Buttons/FinishButton'
import {PauseInfoModal} from '../components/Modal/PauseInfoModal'
import {FinishCancelButton} from '../components/Buttons/FinishCancelButton'
import {OrderRegisterButton} from '../components/Buttons/OrderRegisterButton'
import {LotDeliveryInfoModal} from '../components/Modal/LotDeliveryInfoModal'
import DaumAddressModal from "../components/InputBox/DaumAddressModal";
import {subFactorySearchModal} from "../components/Modal/SearchModalTest/subFactorySearchModal";
import {LotInputInfoModal} from '../components/Modal/LotInputInfoModal'
import placeholder from "lodash/fp/placeholder";
import {OnClickContainer} from '../components/InputBox/OnClickContainer'


export const columnlist: any = {
  member: [
    {key: 'name', editor: TextEditor},
    {key: 'appointment', editor: TextEditor},
    {key: 'telephone', editor: TextEditor},
    {key: 'email', editor: TextEditor},
    {key: 'authority', formatter: AuthoritySearchModal},
    // {key: 'authority', formatter: DropDownEditor, selectList: []},
    {key: 'tmpId', editor: TextEditor},
    {key: 'password', editor: TextEditor},
    {key: 'password-confirm', editor: TextEditor},
    {key: 'profile', formatter: FileEditer, type:"image"},
  ],
  factory: [
    {key: 'name', name: '공장명', width: 240, editor: TextEditor, formatter: PlaceholderBox, placeholder: '공장명 입력'},
    {key: 'address', name: '공장 주소', width: 480, editor: TextEditor},
    {key: 'manager', name: '담당자', width: 120, formatter: SearchModalTest, type: 'user'},
    {key: 'appointment', name: '직책', width: 120, formatter: PlaceholderBox, placeholder: '자동 입력'},
    {key: 'telephone', name: '전화번호', width: 120, formatter: PlaceholderBox, placeholder: '자동 입력'},
    {key: 'description', name: '비고', width: 120, editor: TextEditor, formatter: PlaceholderBox, placeholder: '내용 입력'},
    {key: 'affiliated_id', name: '공장 세분화', width: 120, formatter: /*IdnfoModal*/ FactoryInfoModal, type: 'factoryRegister', summaryType: 'factory'},
  ],
  customer: [
    {key: 'name', editor: TextEditor},
    {key: 'rep', editor: TextEditor},
    {key: 'manager', editor: TextEditor},
    {key: 'telephone', editor: TextEditor},
    {key: 'cellphone', editor: TextEditor},
    {key: 'fax', editor: TextEditor},
    {key: 'address', editor: TextEditor},
    {key: 'crn', editor: TextEditor},
    {key: 'photo', formatter: FileEditer},
  ],
  model: [
    {key: 'customer_id', formatter: SearchModalTest, type: 'customer'},
    {key: 'crn'},
    {key: 'model', editor: TextEditor},
  ],
  process: [
    {key: 'name', editor: TextEditor},
  ],
  machine:[
    {key: 'name', editor: TextEditor},
    {key: 'type', formatter: DropDownEditor, selectList: [
        {pk: 0, name: "선택없음"},
        {pk: 1, name: "프레스"},
        {pk: 2, name: "로봇"},
        {pk: 3, name: "용접기"},
        {pk: 4, name: "밀링"},
        {pk: 5, name: "선반"},
        {pk: 6, name: "탭핑기"},
      ]},
    {key: 'madeAt', editor: CalendarBox},
    {key: 'mfrCode', editor: TextEditor},
    {key: 'user_id', formatter: SearchModalTest, type: 'member'},
    {key: 'manufacturer', editor: TextEditor},
    {key: 'photo', formatter: FileEditer},
    {key: 'qualify', formatter: FileEditer},
    {key: 'capacity', formatter: FileEditer},
    {key: 'guideline', formatter: FileEditer},
    {key: 'interwork', formatter: DropDownEditor, selectList: [
        {pk: 'true', name: '유'},
        {pk: 'false', name: '무'}
      ]},
    {key: 'tons', editor: TextEditor, formatter: UnitContainer, unitData: 'T'},
    {key: 'volt', editor: TextEditor, formatter: UnitContainer, unitData: 'V'},
  ],
  machineV2:[ //기계기준정보
    {key: 'mfrName',name: '기계 제조사',  editor: TextEditor, width: 118},
    {key: 'name', name: '기계 이름', editor: TextEditor, width: 118},
    {key: 'type', name: '기계 종류', formatter: DropDownEditor, headerRenderer: HeaderFilter,
      options:[
        {status: undefined, name: "기계 종류"},
        {status: 0, name: "선택없음"},
        {status: 1, name: "프레스"},
        {status: 2, name: "로봇"},
        {status: 3, name: "용접기"},
        {status: 4, name: "밀링"},
        {status: 5, name: "선반"},
        {status: 6, name: "탭핑기"},
      ],
      selectList: [
        {pk: 0, name: "선택없음"},
        {pk: 1, name: "프레스"},
        {pk: 2, name: "로봇"},
        {pk: 3, name: "용접기"},
        {pk: 4, name: "밀링"},
        {pk: 5, name: "선반"},
        {pk: 6, name: "탭핑기"},
      ], width: 118},
    {key: 'weldingType', name: '용접 종류', formatter: DropDownEditor, selectList: [
        {pk: 0, name: "선택없음"},
        {pk: 1, name: "아르곤"},
        {pk: 2, name: "스팟"},
        {pk: 3, name: "통합"},
      ], width: 118},
    {key: 'madeAt', name: '제조 연월일', formatter: CalendarBox, width: 118},
    {key: 'mfrCode', name: '제조 번호(필수)', editor: TextEditor, width: 118},
    {key: 'manager', name: '담당자', formatter: SearchModalTest, type: 'user', width: 118},
    {key: 'photo', name: '기계사진', formatter: FileEditer, width: 118, type:"image"},
    {key: 'qualify', name: '스펙 명판 사진', formatter: FileEditer, width: 118, type:"image"},
    {key: 'capacity', name: '능력 명판 사진', formatter: FileEditer, width: 118, type:"image"},
    {key: 'guideline', name: '사용 설명서', formatter: FileEditer, width: 118, type:"image"},
    {key: 'interwork', name: '오버홀 유무', formatter: DropDownEditor, selectList: [
        {pk: 'true', name: '유'},
        {pk: 'false', name: '무'}
      ], width: 118},
    {key: 'device_id', name: '주변장치', formatter: /*InfoModal*/ DeviceInfoModal, width: 118, type: 'deviceRegister', summaryType: 'device'},
    {key: 'tons', name: '톤 수',editor: TextEditor, formatter: UnitContainer, unitData: 'T', width: 118},
    {key: 'volt', name: '사용 전압',editor: TextEditor, formatter: UnitContainer, unitData: 'V', width: 118},
    {key: 'factory_id', name: '공장명', width: 118, formatter: SearchModalTest, type: 'factory',},
    {key: 'affiliated_id',name: '공장 세분화명', width: 118, formatter: subFactorySearchModal /*FactoryInfoModal*/, type: 'subFactory',},
      {key: 'check',name: '일상 점검', width: 118, formatter: subFactorySearchModal /*FactoryInfoModal*/, type: 'subFactory',},
    {key: 'product_id',name: '생산 품목', width: 118, formatter: ProductInfoModal, type:"machine", headerType:[{name: "기계명"}]},
  ],
  device: [
    {key: 'mfrName', name: '장치 제조사', editor: TextEditor},
    {key: 'name', name: '장치 이름', editor: TextEditor},
    {key: 'type', name: '장치 종류', formatter: DropDownEditor,headerRenderer: HeaderFilter,
      options:[
        {status: null, name: "장치 종류"},
        {status: 0, name: "선택 없음"},
        {status: 1, name: "미스피드 검출장치"},
        {status: 2, name: "하사점 검출장치"},
        {status: 3, name: "로드모니터"},
        {status: 4, name: "앵글시퀀서"},
        {status: 5, name: "엔코더"},
        {status: 6, name: "통관센서"},
        {status: 7, name: "유틸리티 센서"},
          ],
      selectList: [
        {pk: 0, name: "선택없음"},
        {pk: 1, name: "미스피드 검출장치"},
        {pk: 2, name: "하사점 검출장치"},
        {pk: 3, name: "로드모니터"},
        {pk: 4, name: "앵글시퀀서"},
        {pk: 5, name: "엔코더"},
        {pk: 6, name: "통관센서"},
        {pk: 7, name: "유틸리티 센서"},
      ]},
    {key: 'madeAt', name: '제조 연월일', formatter: CalendarBox},
    {key: 'mfrCode', name: '제조 번호(필수)', editor: TextEditor},
    {key: 'manager', name: '담당자', formatter: SearchModalTest, type:"user"},
    {key: 'photo', name: '장치사진', formatter: FileEditer, type:"image"},
    {key: 'qualify', name: '스펙 명판 사진', formatter: FileEditer, type:"image"},
    {key: 'capacity', name: '능력 명판 사진', formatter: FileEditer, type:"image"},
    {key: 'guideline', name: '사용 설명서', formatter: FileEditer, type:"image"},
    {key: 'factory_id', name: '공장명', formatter: SearchModalTest, type:"factory"},
    {key: 'affiliated_id',name: '공장 세분화명', formatter: subFactorySearchModal, type:"subFactory" /*FactoryInfoModal*/},
  ],
  product: [
    {key: 'customer_id', formatter: CustomerSearchModal, searchType: 'product'},
    {key: 'cm_id', formatter: ModelSearchModal, searchType: 'product'},
    {key: 'code', editor: TextEditor},
    {key: 'name', editor: TextEditor},
    {key: 'texture', editor: TextEditor},
    {key: 'depth', editor: TextEditor, formatter: UnitContainer, unitData: 'mm', toFix: 2},
    {key: 'width', editor: TextEditor, formatter: UnitContainer, unitData: 'mm'},
    {key: 'height', editor: TextEditor, formatter: UnitContainer, unitData: 'mm'},
    {key: 'type', formatter: DropDownEditor, selectList: [
        {pk: 'COIL', name: 'COIL'},
        {pk: 'SHEET', name: 'SHEET'}
      ]},
    {key: 'unitWeight', editor: TextEditor, formatter: UnitContainer, unitData: 'kg', searchType: 'rawin'},
    {key: 'pp_id', formatter: CellButtonComponent, },
  ],
  productV1u: [
    {key: 'customer_id', name: '거래처', formatter: SearchModalTest, type: 'customer', placeholder: '-'},
    {key: 'cm_id', name: '모델', formatter: SearchModalTest, type: 'customerModel', placeholder: '-'},
    {key: 'code', name: 'CODE', editor: TextEditor, formatter: PlaceholderBox, placeholder: 'CODE 입력'},
    {key: 'name', name: '품명', editor: TextEditor, formatter: PlaceholderBox, placeholder: '품명 입력'},
    {key: 'type', name: '품목 종류',  formatter: DropDownEditor, selectList: [
        {pk: '0', name: '반제품'},
        {pk: '1', name: '재공품'},
        {pk: '2', name: '완제품'},
      ]},
    {key: 'unit', name: '단위', formatter: DropDownEditor, selectList: [
        {pk: 'EA', name: 'EA'},
        {pk: 'g', name: 'g'},
        {pk: 'kg', name: 'kg'},
        {pk: 'Ton', name: 'Ton'},
        {pk: 'ml', name: 'ml'},
        {pk: 'L', name: 'L'},
      ]},
    {key: 'bom_root', name: 'BOM', formatter: BomInfoModal, type:"bomRegister"},
    {key: 'process_id', name: '생산 공정', formatter: /*ProcessSearchModal*/ SearchModalTest, type:"process"},
    {key: 'mold_id', name: '금형', formatter: MoldInfoModal},
    {key: 'machine_id', name: '기계', formatter: MachineInfoModal},
    {key: 'standard_uph', name: '기준 UPH', editor: TextEditor, formatter: PlaceholderBox, placeholder: 0},
  ],
  // rawmaterial: [
  //   {key: 'customer_id',},
  //   {key: 'cm_id', },
  //   {key: 'code', },
  //   {key: 'name', },
  //   {key: 'texture',},
  //   {key: 'depth', formatter: UnitContainer, unitData: 'T'},
  //   {key: 'width', formatter: UnitContainer, unitData: 'mm'},
  //   {key: 'height', formatter: UnitContainer, unitData: 'mm'},
  //   {key: 'type', },
  // ],
  rawmaterial: [
    {key: 'code', name: '원자재 CODE', editor: TextEditor},
    {key: 'name', name: '원자재 품명', editor: TextEditor},
    {key: 'texture', name: '재질', editor: TextEditor},
    {key: 'depth', name: '두께', editor: TextEditor, formatter: UnitContainer, unitData: 'T'},
    {key: 'width', name: '가로(COIL 폭)', editor: TextEditor, formatter: UnitContainer, unitData: 'mm'},
    {key: 'height', name: '세로(Feeder)', editor: TextEditor, formatter: UnitContainer, unitData: 'mm'},
    {key: 'type', name: '재질 종류', formatter: DropDownEditor, selectList: [
        {pk: 1, name: 'COIL'},
        {pk: 2, name: 'SHEET'}
      ]},
    {key: 'stock', name: '원자재 재고량', formatter: UnitContainer, unitData: 'kg', searchType: 'rawin'},
    {key: 'customer_id', name: '거래처', formatter: SearchModalTest, type: 'customer' },
    {key: 'expiration', name: '사용기준일', editor: TextEditor, formatter: UnitContainer, unitData: '일', placeholder: '기준일 입력'},
  ],
  submaterial: [
    {key: 'code', name: '부자재 CODE', editor: TextEditor, formatter: PlaceholderBox, placeholder: 'CODE 입력'},
    {key: 'name', name: '부자재 품명', editor: TextEditor, formatter: PlaceholderBox, placeholder: '품명 입력'},
    {key: 'unit', name: '단위', formatter: DropDownEditor, selectList: [
        {pk: 'EA', name: 'EA'},
        {pk: 'g', name: 'g'},
        {pk: 'kg', name: 'kg'},
        {pk: 'Ton', name: 'Ton'},
        {pk: 'ml', name: 'ml'},
        {pk: 'L', name: 'L'},
      ]},
    {key: 'stock', name: '부자재 재고량', formatter: UnitContainer, type: 'selectUnit'},
    {key: 'customer_id', name: '거래처',  formatter: SearchModalTest, type: 'customer'},
  ],
  mold: [
    {key: 'customer_id', },
    {key: 'cm_id', },
    {key: 'code', },
    {key: 'name', },
    {key: 'seq', },
    {key: 'process_id', },
    {key: 'mold_name'},
    {key: 'cavity', },
    {key: 'spm', editor: TextEditor},
    {key: 'slideHeight', editor: TextEditor},
    {key: 'limit', editor: TextEditor},
    {key: 'inspect', editor: TextEditor},
    {key: 'current', editor: TextEditor},

  ],
  moldV2: [
    {key: 'code', name: 'CODE', editor: TextEditor, formatter: PlaceholderBox, placeholder: 'CODE 입력' },
    {key: 'name', name: '금형명', editor: TextEditor,formatter: PlaceholderBox, placeholder: '금형명 입력'},
    {key: 'cavity', name: '캐비티',editor: TextEditor,formatter: UnitContainer, unitData: 'EA', placeholder: '0'},
    {key: 'spm', name: 'SPM',editor: TextEditor,formatter: PlaceholderBox, placeholder: '0'},
    {key: 'slideHeight', name: '슬라이드 위치',editor: TextEditor,formatter: PlaceholderBox, placeholder: '0'},
    {key: 'limit', name: '최대타수', editor: TextEditor,formatter: PlaceholderBox, placeholder: '타수 입력'},
    {key: 'inspect', name: '점검타수', editor: TextEditor,formatter: PlaceholderBox, placeholder: '타수 입력'},
    // {key: 'inspect', name: '점검주기', editor: TextEditor,formatter: PlaceholderBox, placeholder: '타수 입력'},
    {key: 'current', name: '현재타수', editor: TextEditor,formatter: PlaceholderBox, placeholder: '타수 입력'},
    {key: 'product_id', name: '생산품목', formatter: ProductInfoModal, type:"mold", headerType:[  {code:"CODE", name:"금형명"},
                                                                                                 {cavity:"캐비티", spm:"SPM", slideHeight:"슬라이드 위치"},
                                                                                                 {limit:"최대 타수", inspect:"점검 타수", current:"현재 타수"},
                                                                                              ]
    },
    // {key: 'product_id', name: '생산품목', formatter: InfoModal, type: 'productInfo', summaryType: 'mold'},
  ],
  productprocess: [
    {key: 'customer', name: '거래처명', width:118},
    {key: 'model', name: '모델', width:118},
    {key: 'code', name: 'CODE', width:118},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'seq', name: '공정 순서', width:118},
    {key: 'process_id', name: '공정 종류', width:118, formatter: ProcessSearchModal}, //ProcessSearchModal로 변경
    {key: 'mold_name', name: '금형명', width:118, editor: TextEditor},
    {key: 'cavity', name: '캐비티', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'last', name: '최종 공정 체크', formatter:DropDownEditor ,selectList: [
        {pk: false, name: '-'},
        {pk: true, name: '최종 공정'},
      ], width:118},
    {key: 'wip_name', name: '반제품명', width:118, editor: TextEditor},
  ],
  additionalItem:[
    {key: 'title', editor: TextEditor, name: "추가 항목명", width: 1290},
    {key: 'moddable', formatter: DropDownEditor, selectList: [
        {unit_id: '0', name: "필요"},
        {unit_id: '1', name: "불필요"}
      ], name: "단위 필요 유무"},
    {key: 'unit', formatter: DropDownEditor, selectList: [
        {unit_id: '0', name: "개별관리"},
        {unit_id: '1', name: "통일"},
        {unit_id: '2', name: "없음"},
      ], name: "단위 관리"},
  ],
  rawin: [
    {key: 'customer_id', frozen: true},
    {key: 'cm_id', searchType: 'rawin', frozen: true},
    {key: 'code', formatter: ProductSearchModal, searchType: 'rawin', frozen: true},
    {key: 'name', frozen: true},
    {key: 'texture',},
    {key: 'depth', formatter: UnitContainer, unitData: 'T'},
    {key: 'width', formatter: UnitContainer, unitData: 'mm'},
    {key: 'height', formatter: UnitContainer, unitData: 'mm'},
    {key: 'type', },
    {key: 'amount', editor: TextEditor,formatter: UnitContainer, unitData: 'kg', searchType: 'rawin'},
    {key: 'date', editor: CalendarBox},
    {key: 'number', editor: TextEditor},
    {key: 'current', },
  ],

  rawstock: [
    {key: 'customer_id', frozen: true},
    {key: 'cm_id', frozen: true},
    {key: 'code', frozen: true},
    {key: 'name', frozen: true},
    {key: 'texture'},
    {key: 'depth', formatter: UnitContainer, unitData: 'T'},
    {key: 'width', formatter: UnitContainer, unitData: 'mm'},
    {key: 'height', formatter: UnitContainer, unitData: 'mm'},
    {key: 'type', },
    {key: 'amount',formatter: UnitContainer, unitData: 'kg', searchType: 'rawin'},
    {key: 'date', },
    {key: 'number'},
    {key: 'blanking',formatter: UnitContainer, unitData: 'EA'},
    {key: 'current', formatter: UnitContainer, unitData: 'kg', searchType: 'rawin',},
    {key: 'exhaustion', formatter: DropDownEditor, headerRenderer: HeaderFilter,
      options:[{status:0, name:"재고 현황"},{status:1, name:"사용 가능"}],
      selectList: [
        {pk: false, name: '-'},
        {pk: true, name: '사용완료'}
      ]},
  ],

  rawinV1u: [
    {key: 'rm_id',name:'원자재 CODE', formatter: SearchModalTest, type: 'rawmaterial', frozen: true, placeholder: '원자재 CODE'},
    {key: 'name', name:'원자재 품명', frozen: true, formatter: PlaceholderBox, placeholder:'자동 입력'},
    {key: 'texture', name:'재질', formatter: PlaceholderBox, placeholder:'자동 입력'},
    {key: 'depth', name:'두께', formatter: UnitContainer, unitData: 'T', placeholder: '0'},
    {key: 'width', name:'가로(COIL 폭)', formatter: UnitContainer, unitData: 'mm', placeholder: '0' },
    {key: 'height', name:'세로(Feeder)', formatter: UnitContainer, unitData: 'mm', placeholder: '0'},
    {key: 'type', name:'재질 종류',formatter: PlaceholderBox, placeholder:'자동 입력' },
    {key: 'customer_id', name:'거래처', formatter: PlaceholderBox, placeholder:'자동 입력' },
    {key: 'expiration', name:'사용 기준일', editor: TextEditor,formatter: UnitContainer, unitData: '일', placeholder: '자동 입력' },
    {key: 'amount', name:'입고량', editor: TextEditor,formatter: UnitContainer, searchType: 'rawin', unitData: 'kg', placeholder: '0'},
    {key: 'date', name:'입고일', formatter: CalendarBox},
    {key: 'lot_number', name:'원자재 LOT 번호', editor: TextEditor, formatter: PlaceholderBox, placeholder: 'LOT 입력'},
  ],

  rawstockV1u: [
    {key: 'elapsed', name: '경과일', formatter: UseDateCell, width: 118},
    {key: 'rm_id',name:'원자재 CODE', formatter: PlaceholderBox, placeholder: '원자재 CODE', width: 118},
    {key: 'name', name:'원자재 품명', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'texture', name:'재질', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'depth', name:'두께', formatter: UnitContainer, unitData: 'T', placeholder: '0', width: 118},
    {key: 'width', name:'가로(COIL 폭)', formatter: UnitContainer, unitData: 'mm', placeholder: '0', width: 118 },
    {key: 'height', name:'세로(Feeder)', formatter: UnitContainer, unitData: 'mm', placeholder: '0', width: 118},
    {key: 'type', name:'재질 종류',formatter: PlaceholderBox, placeholder:'자동 입력', width: 118 },
    {key: 'warehousing',name: '입고량', formatter: UnitContainer, unitData: 'kg', searchType: 'rawin', width: 118},
    {key: 'date', name: '입고일', width: 118},
    {key: 'lot_number', name: '원자재 LOT 번호', width: 118},
    {key: 'current', name: 'LOT 재고량', formatter: UnitContainer, unitData: 'kg', searchType: 'rawin',width: 118},
    {key: 'exhaustion',  headerRenderer: HeaderFilter, width: 118,
      options:[{status:0, name:"재고 현황"},{status:1, name:"사용 가능"}],
      selectList: [
        {pk: false, name: '-'},
        {pk: true, name: '사용완료'}
      ]},
    {key: 'customer_id', name: '거래처', width: 118},
    {key: 'expiration', name: '사용 기준일', formatter: UnitContainer, unitData: '일', width: 118},
  ],

  rawstockModify: [
    {key: 'rm_id',name:'원자재 CODE', formatter: PlaceholderBox, placeholder: '원자재 CODE', width: 118},
    {key: 'name', name:'원자재 품명', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'texture', name:'원자재 재질', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'depth', name:'두께', formatter: UnitContainer, unitData: 'T', placeholder: '0', width: 118},
    {key: 'width', name:'가로(COIL 폭)', formatter: UnitContainer, unitData: 'mm', placeholder: '0', width: 118 },
    {key: 'height', name:'세로(Feeder)', formatter: UnitContainer, unitData: 'mm', placeholder: '0', width: 118},
    {key: 'type', name:'재질 종류',formatter: PlaceholderBox, placeholder:'자동 입력', width: 118 },
    {key: 'customer_id', name: '거래처', width: 118},
    {key: 'expiration', name: '사용 기준일', formatter: UnitContainer, unitData: '일', width: 118},
    {key: 'warehousing',name: '입고량', editor: TextEditor, formatter: UnitContainer, unitData: 'kg', searchType: 'rawin', width: 118},
    {key: 'exhaustion', formatter: DropDownEditor, headerRenderer: HeaderFilter, width: 118,
      options:[{status:0, name:"재고 현황"},{status:1, name:"사용 가능"}],
      selectList: [
        {pk: false, name: '-'},
        {pk: true, name: '사용완료'}
      ]},
    {key: 'date', name: '입고일', formatter: CalendarBox, width: 118},
    {key: 'lot_number', name: '원자재 LOT 번호', editor: TextEditor, width: 118},
  ],

  subinV1u: [
    {key: 'wip_id',name:'부자재 CODE', formatter: SearchModalTest, type: 'submaterial', frozen: true, placeholder: '부자재 CODE'},
    {key: 'name', name:'부자재 품명', frozen: true, formatter: PlaceholderBox, placeholder:'자동 입력'},
    {key: 'unit', name:'단위', formatter: PlaceholderBox, placeholder:'자동 입력'},
    {key: 'customer_id', name:'거래처', formatter: PlaceholderBox, placeholder:'자동 입력' },
    {key: 'amount', name:'입고량', editor: TextEditor,formatter: UnitContainer, unitData: '', placeholder: '0'},
    {key: 'date', name:'입고일', formatter: CalendarBox},
    {key: 'lot_number', name:'부자재 LOT 번호', editor: TextEditor, formatter: PlaceholderBox, placeholder: 'LOT 입력'},
  ],

  substockV1u: [
    {key: 'wip_id',name:'부자재 CODE', formatter: PlaceholderBox, placeholder: '부자재 CODE', width: 118},
    {key: 'name', name:'부자재 품명', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'unit', name:'단위', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'customer_id', name:'거래처', width: 118},
    {key: 'warehousing',name: '입고량', searchType: 'rawin', width: 118},
    {key: 'date', name: '입고일', width: 118},
    {key: 'lot_number', name: '부자재 LOT 번호', width: 118},
    {key: 'current', name: 'LOT 재고량', width: 118},
  ],

  substockModify: [
    {key: 'wip_id',name:'부자재 CODE', formatter: PlaceholderBox, placeholder: '원자재 CODE', width: 118},
    {key: 'name', name:'부자재 품명', formatter: PlaceholderBox, placeholder:'자동 입력', width: 118},
    {key: 'unit', name:'단위',formatter: PlaceholderBox, placeholder:'자동 입력', width: 118 },
    {key: 'customer_id', name:'거래처', formatter: PlaceholderBox, placeholder: '0', width: 118},
    {key: 'warehousing',name: '입고량', editor: TextEditor, width: 118},
    {key: 'date', name: '입고일', formatter: CalendarBox, width: 118},
    {key: 'lot_number', name: '부자재 LOT 번호', editor: TextEditor, width: 118},
    {key: 'exhaustion', formatter: DropDownEditor, headerRenderer: HeaderFilter, width: 118,
      options:[{status:0, name:"재고 현황"},{status:1, name:"사용 가능"}],
      selectList: [
        {pk: false, name: '-'},
        {pk: true, name: '사용완료'}
      ]},
  ],

  baseItem: [
    {key: 'title', editor: TextEditor, name: "기본 항목명"},
  ],
  pause: [
    {key: 'name' , formatter : OnClickContainer}
  ],
  pauseReason: [
    {key: 'index', name:"순번", width:130},
    {key: 'reason', name:"일시정지 유형", width:1200, editor: TextEditor},
    {key: 'moveButtons', width:200, formatter:MoveButtons,},
  ],
  defectReason:[
    {key: 'index', name:"순번", width:130},
    {key: 'reason', name:"불량 유형", width:1200, editor: TextEditor},
    {key: 'moveButtons', width:200, formatter:MoveButtons,},
  ],
  stock:[
    {key:'customer_id'},
    {key:'customer_name'},
    {key:'cm_id', },
    {key:'code',  },
    {key:'name',  },
    {key:'unused',  formatter: UnitContainer, unitData: 'kg'},
    {key:'wip', formatter: UnitContainer, unitData: 'EA'},
    {key:'current_stock', formatter: UnitContainer, unitData: 'EA'},
    {key:'expectation', formatter: UnitContainer, unitData: 'EA'},
    {key:'inverse_expectation', formatter: UnitContainer, unitData: 'EA'},
  ],
  stockProduct: [
    {key:'customer_id', name:"거래처명"},
    {key:'cm_id', name:"모델"},
    {key:'code', name:"CODE"},
    {key:'name', name:"품명"},
  ],
  stockDate: [
    {key:'title', name:"생산/납품" },
  ],
  operationRegister: [
    {key: 'date', editor: CalendarBox, name: '지시 날짜'},
    {key: 'customer_id',  name: '거래처명'},
    {key: 'cm_id', name: '모델'},
    {key: 'code', formatter: ProductSearchModal, searchType: 'operation', name: 'CODE'},
    {key: 'name', name: '품명'},
    {key: 'texture', name: '재질'},
    {key: 'seq', name: '공정 순서'},
    {key: 'process_id', name: '공정 종류'},
    {key: 'mold', name: '금형명'},
    {key: 'machine_id', name: '기계 선택',
      formatter: /*MachineSearchModal*/ OperationMachineSearchModal
      // formatter: MachineSearchModal
    },
    {key: 'goal', name: '목표 생산량', editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'ln_id', name: '원자재 Lot 번호', formatter: RawMaterialSearchModal, searchType: 'operation', disableType: 'record'},
  ],
  operationList: [
    {key: 'status', formatter: StatusComponent, headerRenderer: HeaderFilter,
      options:[{status:-1, name:"상태"}, {status:0, name:"시작 전"}, {status:1, name:"작업중"}, {status:2, name:"일시정지"}, {status:3, name:"작업종료"}, {status:4, name:"미완료"}]},
    {key: 'identification'},
    {key: 'date', editor: CalendarBox},
    {key: 'customer_id'},
    {key: 'cm_id'},
    {key: 'code'},
    {key: 'name'},
    {key: 'texture'},
    {key: 'seq'},
    {key: 'process_id'},
    {key: 'mold_id'},
    {key: 'machine_id', formatter: MachineSearchModal},
    {key: 'goal', editor: TextEditor},
    {key: 'ln_id', formatter: RawMaterialSearchModal, disableType: 'record'},
  ],
  recordRegister: [
    {key: 'osd_id', name: '지시 고유 번호', formatter: OperationSearchModal, width:118},
    {key: 'date', name: '지시 날짜', editor: CalendarBox, width:118, disableType: 'record'},
    {key: 'customer_id', name: '거래처명', width:200, disableType: 'record'},
    {key: 'cm_id', name: '모델', width:200, disableType: 'record'},
    {key: 'code', name: 'CODE', formatter: ProductSearchModal, width:118, disableType: 'record'},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'seq', name: '공정 순서', width:118, formatter: ProcessSeqModal, disableType: 'record'},
    {key: 'process_id', name: '공정 종류', width:118, disableType: 'record'},
    {key: 'mold_id', name: '금형명', width:118, disableType: 'record'},
    {key: 'machine_id', name: '기계 선택', width:118, formatter: MachineSearchModal, disableType: 'record'},
    {key: 'goal', name: '목표 생산량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA', searchType: 'record'},
    {key: 'ln_id', name: '원자재 Lot 번호', width:118, formatter: RawMaterialSearchModal, disableType: 'record'},
    {key: 'good_quantity', name: '양품 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantities', name: '불량 유형', width:118, formatter: PoorQuantityModal, unitData: 'EA'},
    {key: 'poor_quantity', name: '불량 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    // {key: 'poor_quantity', name: '불량 수량', width:118, formatter: PoorQuantityModal, unitData: 'EA'},
    {key: 'start', name: '작업 시작 일시', width:250, formatter: DatetimePickerBox},
    {key: 'end', name: '작업 종료 일시', width:250, formatter: DatetimePickerBox},
    {key: 'paused_time', name: '일시 정지 시간', width:118, formatter:PauseModal},
    {key: 'user_id', name: '작업자', width:118, formatter: MemberSearchModal},
  ],
  workerRecordReigster: [
    {key: 'osd_id', name: '지시 고유 번호', formatter: OperationSearchModal, width:118},
    {key: 'date', name: '지시 날짜', editor: CalendarBox, width:118, disableType: 'record'},
    {key: 'customer_id', name: '거래처명', formatter: CustomerSearchModal, width:200, disableType: 'record'},
    {key: 'cm_id', name: '모델', formatter: ModelSearchModal, width:200, disableType: 'record'},
    {key: 'code', name: 'CODE', formatter: ProductSearchModal, width:118, disableType: 'record'},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'seq', name: '공정 순서', width:118, formatter: ProcessSeqModal, disableType: 'record'},
    {key: 'process_id', name: '공정 종류', width:118, disableType: 'record'},
    {key: 'mold_id', name: '금형명', width:118, disableType: 'record'},
    {key: 'machine_id', name: '기계 선택', width:118, formatter: MachineSearchModal, disableType: 'record'},
    {key: 'goal', name: '목표 생산량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA', searchType: 'record'},
    {key: 'ln_id', name: '원자재 Lot 번호', width:118, formatter: RawMaterialSearchModal, disableType: 'record'},
    {key: 'good_quantity', name: '양품 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantity', name: '불량 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'start', name: '작업 시작 일시', width:250, formatter: DatetimePickerBox},
    {key: 'end', name: '작업 종료 일시', width:250, formatter: DatetimePickerBox},
    {key: 'paused_time', name: '일시 정지 시간', width:118, formatter:PauseModal},
    {key: 'user_id', name: '작업자', width:118, formatter: MemberSearchModal},
  ],
  recordList: [
    {key: 'identification', name: '지시 고유 번호', width:118},
    {key: 'date', name: '지시 날짜', width:118},
    {key: 'customer_id', name: '거래처명', width:118},
    {key: 'cm_id', name: '모델', width:118},
    {key: 'code', name: 'CODE', width:118},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'seq', name: '공정 순서', width:118},
    {key: 'process_id', name: '공정 종류', width:118},
    {key: 'mold_id', name: '금형명', width:118},
    {key: 'machine_id', name: '기계 선택', width:118},
    {key: 'goal', name: '목표 생산량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'ln_id', name: '원자재 lot번호', width:118, formatter: RawMaterialSearchModal},
    {key: 'good_quantity', name: '양품 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantity', name: '불량 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantities', name: '불량 유형', width:118, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'list'},
    // {key: 'poor_quantity', name: '불량 수량', width:118, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'list'},
    {key: 'achievement', width:118, formatter: UnitContainer, unitData: '%'},
    {key: 'start', name: '작업 시작 일시', width:250, formatter: DatetimePickerBox},
    {key: 'end', name: '작업 종료 일시', width:250, formatter: DatetimePickerBox},
    {key: 'paused_time', name: '일시 정지 시간', width:118, formatter:PauseModal, searchType: 'list'},
    {key: 'uph', name: 'UPH', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'worker', name: '작업자', width:118, formatter:MemberSearchModal, searchType: 'list'},
  ],
  workerRecordList: [
    {key: 'identification', name: '지시 고유 번호', width:118},
    {key: 'date', name: '지시 날짜', width:118},
    {key: 'customer_id', name: '거래처명', width:118},
    {key: 'cm_id', name: '모델', width:118},
    {key: 'code', name: 'CODE', width:118},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'seq', name: '공정 순서', width:118},
    {key: 'process_id', name: '공정 종류', width:118},
    {key: 'mold_id', name: '금형명', width:118},
    {key: 'machine_id', name: '기계 선택', width:118},
    {key: 'goal', name: '목표 생산량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'ln_id', name: '원자재 lot번호', width:118, formatter: RawMaterialSearchModal},
    {key: 'good_quantity', name: '양품 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantity', name: '불량 수량', width:118, editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
    // {key: 'poor_quantities', name: '불량 유형', width:118, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'list'},
    // {key: 'poor_quantity', name: '불량 수량', width:118, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'list'},
    {key: 'achievement', width:118, formatter: UnitContainer, unitData: '%'},
    {key: 'start', name: '작업 시작 일시', width:250, formatter: DatetimePickerBox},
    {key: 'end', name: '작업 종료 일시', width:250, formatter: DatetimePickerBox},
    {key: 'paused_time', name: '일시 정지 시간', width:118, formatter:PauseModal, searchType: 'list'},
    {key: 'uph', name: 'UPH', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'worker', name: '작업자', width:118, formatter:MemberSearchModal, searchType: 'list'},
  ],
  recordSumList: [
    {key: 'identification', name: '지시 고유 번호', width:118},
    {key: 'latest_date', name: '지시 날짜', width:118},
    {key: 'customer_id', name: '거래처명', width:118},
    {key: 'cm_id', name: '모델', width:118},
    {key: 'code', name: 'CODE', width:118},
    {key: 'name', name: '품명', width:118},
    {key: 'texture', name: '재질', width:118},
    {key: 'used_sequences', name: '공정 순서', width:118},
    {key: 'used_processes', name: '공정 종류', width:118},
    {key: 'used_molds', name: '금형명', width:118},
    {key: 'used_machines', name: '기계 선택', width:118},
    {key: 'avg_goal', name: '목표 생산량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'used_lot_numbers', name: '원자재 lot번호', width:118},
    {key: 'avg_good_quantity', name: '양품 수량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'avg_poor_quantity', name: '불량 수량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'avg_confirm_quantities', name: '불량 유형', width:118, formatter: UnitContainer, unitData: 'EA'},
    // {key: 'poor_quantity', name: '불량 수량', width:118, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'list'},
    {key: 'avg_achievement', name: '목표 달성률', width:118, formatter: UnitContainer, unitData: '%'},
    {key: 'oldest_start', name: '작업 시작 일시', width:250,},
    {key: 'latest_end', name: '작업 종료 일시', width:250, },
    {key: 'avg_paused_time', name: '일시 정지 시간', width:118,},
    {key: 'avg_uph', name: 'UPH', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'workers', name: '작업자', width:118, formatter: RecordDetailFormatter, searchType: 'list'},
  ],
  recordSumDetailList: [
    {key: 'ln_id', name: '원자재 lot번호', width:118},
    {key: 'good_quantity', name: '양품 수량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantity', name: '불량 수량', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'poor_quantities', name: '불량 유형', width: 150, formatter: PoorQuantityModal, unitData: 'EA', searchType: 'disable'},
    {key: 'achievement', name: '목표 달성률',width:118, formatter: UnitContainer, unitData: '%'},
    {key: 'start', name: '작업 시작 일시', width:250,},
    {key: 'end', name: '작업 종료 일시', width:250, },
    {key: 'paused_time', name: '일시 정지 시간', width:118, formatter:PauseModal, searchType: 'disable'},
    {key: 'uph', name: 'UPH', width:118, formatter: UnitContainer, unitData: 'EA'},
    {key: 'worker', name: '작업자', width:118,},
  ],
  workStandardList: [
    {key: 'customer', name: '거래처',width: 120},
    {key: 'model', name: '모델', width: 120},
    {key: 'code', name: 'CODE',width: 464},
    {key: 'material_name', name: '품명',width: 464},
    {key: 'type', name: '품목 종류', width: 120, selectList: [
        {pk: '0', name: '반제품'},
        {pk: '1', name: '재공품'},
        {pk: '2', name: '완제품'},
      ]},
    {key: 'work_standard_image', name: '작업 표준서', formatter: FileEditer, type:"image"},
  ],
  midrange: [
    {key: 'samples', name: '시료 개수 선택 (최소 1 ~ 최대 10개)', formatter: DropDownEditor, selectList: [
        {pk: 'one', name: 1},
        {pk: 'two', name: 2},
        {pk: 'three', name: 3},
        {pk: 'four', name: 4},
        {pk: 'five', name: 5},
        {pk: 'six', name: 6},
        {pk: 'seven', name: 7},
        {pk: 'eight', name: 8},
        {pk: 'nine', name: 9},
        {pk: 'ten', name: 10},
      ]}
  ],
  midrangeDetail: [
    {key: 'samples', name: '시료 개수 선택 (최소 1 ~ 최대 10개)'}
  ],
  midrangeExam: [
    {key: 'customer', name: '거래처',width: 240},
    {key: 'model', name: '모델', width: 424},
    {key: 'code', name: 'CODE', width: 432},
    {key: 'material_name', name: '품명', width: 360},
    {key: 'type', name: '품목 종류',width: 120},
  ],
  midrangeExamDetail: [
    {key: 'customer', name: '거래처',width: 240},
    {key: 'model', name: '모델', width: 424},
    {key: 'code', name: 'CODE', width: 432},
    {key: 'material_name', name: '품명', width: 360},
    {key: 'type', name: '품목 종류',width: 120},
  ],
  midrangeLegendary: [
    {key: 'legendary', name: '범례',width: 968, formatter: PlaceholderBox, placeholder: '범례 입력', editor: TextEditor},
    {key: 'LegendaryExplain', name: '범례 설명', width: 608, formatter: PlaceholderBox, placeholder: '범례 설명 입력', editor: TextEditor},
  ],
  midrangeLegendaryDetail: [
    {key: 'legendary', name: '범례',width: 968,},
    {key: 'LegendaryExplain', name: '범례 설명', width: 608},
  ],
  midrangeInspectionItem: [
    {key: 'name', name: '검사 항목',width: 480, formatter: PlaceholderBox, placeholder: '검사 항목 입력', editor: TextEditor},
    {key: 'unit', name: '단위', width: 120, formatter: DropDownEditor, selectList: [
        {pk: 'mm', name: 'mm'},
        {pk: 'cm', name: 'cm'},
        {pk: 'm', name: 'm'},
        {pk: 'EA', name: 'EA'},
        {pk: 'g', name: 'g'},
        {pk: 'kg', name: 'kg'},
        {pk: 'Ton', name: 'Ton'},
        {pk: 'ml', name: 'ml'},
        {pk: 'L', name: 'L'},
      ]},
    {key: 'standard', name: '점검 기준', width: 424, placeholder: '점검 기준 입력', editor: TextEditor, formatter: UnitContainer,},
    {key: 'error_minimum', name: '최소값(오차범위 최소)', width: 216, formatter: UnitContainer, placeholder: '최소값 입력',editor: TextEditor},
    {key: 'error_maximum', name: '최대값(오차범위 최대)', width: 216, formatter: UnitContainer, placeholder: '최대값 입력',editor: TextEditor},
    {key: 'type', name: '기록 방법', width: 120, formatter: DropDownEditor, selectList: [
        {pk: '0', name: '수치 입력'},
        {pk: '1', name: '범례 적용'},
      ] },
  ],
  midrangeInspectionItemDetail: [
    {key: 'name', name: '검사 항목',width: 480, },
    {key: 'unit', name: '단위', width: 120,},
    {key: 'standard', name: '점검 기준', width: 424, },
    {key: 'error_minimum', name: '최소값(오차범위 최소)', width: 216},
    {key: 'error_maximum', name: '최대값(오차범위 최대)', width: 216, },
    {key: 'type', name: '기록 방법', width: 120},
  ],
  midrangeList: [
    {key: 'contract_id', name: '수주 번호', width: 120},
    {key: 'osId', name: '지시 고유 번호', width: 120},
    {key: 'code', name: 'CODE', width: 120},
    {key: 'name', name: '품명', width: 120},
    {key: 'type', name: '품목 종류', width: 120, selectList: [
        {pk: '0', name: '반제품'},
        {pk: '1', name: '재공품'},
        {pk: '2', name: '완제품'},
      ]},
    {key: 'unit', name: '단위', width: 120},
    {key: 'process_id', name: '생산 공정', width: 120},
    {key: 'ln_id', name: 'LOT 번호', width: 120},
    {key: 'worker', name: '작업자', width: 120 },
    {key: 'start', name: '작업 시작 일시', width: 164},
    {key: 'end', name: '작업 종료 일시', width: 164},
  ],
  qualityDefectTop: [
    {key: 'customer', name: '거래처명', searchType: 'rawin', formatter: PlaceholderBox, placeholder: '자동입력'},
    {key: 'model', name: '모델', searchType: 'rawin', formatter: PlaceholderBox, placeholder: '자동입력'},
    {key: 'code', name: 'CODE', formatter: SearchModalTest, type: 'product'},
    {key: 'name', name: '품명', formatter: PlaceholderBox, placeholder: '자동입력'},
  ],
  qualityDefectContents: [
    {key: 'process_id', name: '공정명', width: 220},
    {key: 'reason', name: '불량 유형', width: 550},
    {key: 'amount', name: '개수', width: 250, headerRenderer: HeaderFilter,
      options:[{status:0, name:"개수"},{status:1, name:"개수 많은순"},{status:2, name:"개수 적은순"}],
     },
  ],
  delivery: [
    {key:"customer_id", name:"거래처명",   },
    {key:"cm_id", name:"모델",  },
    {key:"code", name:"CODE", formatter: /*ProductSearchModal*/ MultipleSelectModal},
    {key:"name", name:"품명"},
    {key:"date", name:"납품 날짜", editor: CalendarBox, maxDate:true},
    {key:"amount", name:"납품 개수", editor: TextEditor, formatter: UnitContainer, unitData: 'EA'},
  ],

  operationRegisterV2: [
    {key:"contract_id", name:"수주 번호", formatter: SearchModalTest, type: 'order', placeholder: '검색', disableType:"true"  },
    {key:"date", name:"지시 날짜", formatter: CalendarBox, },
    {key:"deadline", name:"작업 기한", formatter: CalendarBox,},
    {key:"customer_id", name:"거래처", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key:"cm_id", name:"모델", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput' },
    {key:"product_id", name:"CODE", formatter: SearchModalTest, type: 'product', placeholder: '검색', disableType:"true"},
    {key:"name", name:"품명", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key:"type", name:"품목 종류", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key:"unit", name:"단위", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key:"process_id", name:"생산 공정", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key:"goal", name:"목표 생산량", editor: TextEditor, formatter: PlaceholderBox, placeholder: '0'},
    {key: 'input', name: '자재 선택', formatter: BomRegisterModal, width: 118},
  ],
  operationListV2: [
    {key:"status", name:"상태", width: 118},
    {key:"contract_id", name:"수주 번호", width: 118   },
    {key:"identification", name:"지시 고유 번호", width: 118   },
    {key:"date", name:"지시 날짜", width: 118 },
    {key:"deadline", name:"작업 기한", width: 118 },
    {key:"customer_id", name:"거래처", width: 118},
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118 },
    {key:"name", name:"품명", width: 118},
    {key:"type", name:"품목 종류", width: 118},
    {key:"unit", name:"단위", width: 118},
    {key:"process_id", name:"생산 공정", width: 118},
    {key:"goal", name:"목표 생산량", width: 118},
    {key: 'input', name: '투입 자재', formatter: InputMaterialInfoModal, width: 118, type: 'readonly'},
    {key: 'route_record_register', name: '작업 일보 등록', formatter: WorkRegisterModal, width: 118},
    {key: 'route_record_list', name: '작업 이력', formatter: WorkListModal, width: 118, modalInitData: BomRegisterInit },
    {key: 'total_counter', name: '총 카운터', width: 118 },
    {key: 'total_good_quantity', name: '총 양품 수량', width: 118 },
    {key: 'total_poor_quantity', name: '총 불량 수량', width: 118, formatter: DefectInfoModal, type: 'readonly'},
    {key: 'force_kill', name: '작업완료 처리', formatter: FinishButton, width: 118},
  ],
  operationModifyV2: [
    {key:"contract_id", name:"수주 번호", width: 118},
    {key:"identification", name:"지시 고유 번호", width: 118   },
    {key:"date", name:"지시 날짜", formatter: CalendarBox, width: 118 },
    {key:"deadline", name:"작업 기한", formatter: CalendarBox, width: 118},
    {key:"customer_id", name:"거래처", width: 118},
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118},
    {key:"name", name:"품명", width: 118},
    {key:"type", name:"품목 종류", width: 118},
    {key:"unit", name:"단위", width: 118},
    {key:"process_id", name:"생산 공정", width: 118},
    {key:"goal", name:"목표 생산량", editor: TextEditor, formatter: PlaceholderBox, placeholder: '0'},
    {key: 'input', name: '자재 선택', formatter: BomRegisterModal, width: 118},
  ],
  recordListV2: [
    {key:"contract_id", name:"수주 번호", width: 118},
    {key:"identification", name:"지시 고유 번호", width: 118   },
    {key:"product_id", name:"CODE", width: 118},
    {key:"name", name:"품명", width: 118},
    {key:"type", name:"품목 종류", width: 118},
    {key:"unit", name:"단위", width: 118},
    {key:"process_id", name:"생산 공정", width: 118},
    {key:"lot_number", name:"LOT 번호", width: 118},
    {key:"worker", name:"작업자", width: 118},
    {key:"start", name:"작업 시작 일시", width: 118},
    {key:"end", name:"작업 종료 일시", width: 118},
    {key:"paused_time", name:"일시 정지 시간", formatter: PauseInfoModal, type: 'readonly', modalType: false, width: 118},
    {key:"good_quantity", name:"양품 수량", width: 118},
    {key:"poor_quantity", name:"불량 수량", formatter: DefectInfoModal, type: 'readonly', width: 118},
    {key:"uph", name:"UPH", width: 118},
    {key: 'input', name: '투입 자재', formatter: LotInputInfoModal, width: 118, type: 'readonly'},
    {key: 'mold_id', name: '금형', formatter: MoldListModal, width: 118, modalInitData: BomRegisterInit},
    {key: 'machine_id', name: '기계', formatter: MachineListModal, width: 118, modalInitData: BomRegisterInit},
  ],
  finishListV2: [
    {key:"status", name:"상태", formatter: FinishCancelButton, width: 118},
    {key:"contract_id", name:"수주 번호", width: 118   },
    {key:"identification", name:"지시 고유 번호", width: 118   },
    {key:"date", name:"지시 날짜", width: 118 },
    {key:"deadline", name:"작업 기한", width: 118 },
    {key:"customer_id", name:"거래처", width: 118},
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118 },
    {key:"name", name:"품명", width: 118},
    {key:"type", name:"품목 종류", width: 118},
    {key:"unit", name:"단위", width: 118},
    {key:"process_id", name:"생산 공정", width: 118},
    {key:"goal", name:"목표 생산량", width: 118},
    {key: 'input', name: '투입 자재', formatter: InputMaterialInfoModal, width: 118, type: 'readonly'},
    {key: 'route_record_list', name: '작업 이력', formatter: WorkListModal, width: 118, modalInitData: BomRegisterInit },
    {key: 'total_counter', name: '총 카운터', width: 118 },
    {key: 'total_good_quantity', name: '총 양품 수량', width: 118 },
    {key: 'total_poor_quantity', name: '총 불량 수량', width: 118, formatter: DefectInfoModal},
    {key:"total_uph", name:"총 UPH", width: 118},
  ],
  stockV2: [
    {key:"customer_id", name:"거래처", width: 118},
    {key:"cm_id", name:"모델", width: 118},
    {key:"product_id", name:"CODE", width: 118 },
    {key:"name", name:"품명", width: 118 },
    {key:"type", name:"품목 종류", width: 118 },
    {key:"unit", name:"단위", width: 118   },
    {key: 'bom_root', name: 'BOM', formatter: BomInfoModal, width: 118, type: 'readonly'},
    {key: 'lot_number', name: 'LOT별 재고', formatter: LotInfoModal, width: 118, type: 'readonly'},
    {key:"stock", name:"재고량", width: 118},
  ],
  orderRegister: [
    {key:"date", name:"수주 날짜", formatter: CalendarBox, width: 118, type: "date"},
    {key:"deadline", name:"납품 기한", formatter: CalendarBox, width: 118, type:"deadline"},
    {key:"customer_id", name:"거래처", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"cm_id", name:"모델", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"product_id", name:"CODE", width: 118, formatter: SearchModalTest, type: 'product' },
    {key:"name", name:"품명", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"type", name:"품목 종류", width: 118, formatter: PlaceholderBox, placeholder: '자동입력'   },
    {key:"unit", name:"단위", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"amount", name:"수주량", width: 118, editor: TextEditor, formatter: PlaceholderBox, placeholder: '0' },
  ],
  orderList: [
    {key:"identification", name:"수주 번호", width: 118},
    {key:"date", name:"수주 날짜", width: 118,
      // headerRenderer: HeaderFilter,
      // options:[
      //   {status: undefined, name: "기계 종류"},
      //   {status: 0, name: "선택없음"},
      //   {status: 1, name: "프레스"},
      //   {status: 2, name: "로봇"},
      //   {status: 3, name: "용접기"},
      //   {status: 4, name: "밀링"},
      //   {status: 5, name: "선반"},
      //   {status: 6, name: "탭핑기"},
      // ],
      // selectList: [
      //   {pk: 0, name: "선택없음"},
      //   {pk: 1, name: "프레스"},
      //   {pk: 2, name: "로봇"},
      //   {pk: 3, name: "용접기"},
      //   {pk: 4, name: "밀링"},
      //   {pk: 5, name: "선반"},
      //   {pk: 6, name: "탭핑기"},
      // ],
    },
    {key:"deadline", name:"납품 기한", width: 118},
    {key:"customer_id", name:"거래처", width: 118 },
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118 },
    {key:"name", name:"품명", width: 118 },
    {key:"type", name:"품목 종류", width: 118 },
    {key:"unit", name:"단위", width: 118 },
    {key:"amount", name:"수주량", width: 118 },
    {key:"route_operation_register", name:"지시 고유 번호", width: 118, formatter: OperationInfoModal},
    {key:"shipment_id", name:"납품 수량", width: 118, formatter: DeliveryInfoModal },
    {key:"route_shipment_register", name:"납품 등록", width: 118, formatter: OrderRegisterButton, title: '납품 등록', url: '/mes/delivery/register'   },
  ],
  orderModify: [
    {key:"identification", name:"수주 번호", width: 118},
    {key:"date", name:"수주 날짜", formatter: CalendarBox, width: 118, type: "date"},
    {key:"deadline", name:"납품 기한", formatter: CalendarBox, width: 118, type:"deadline"},
    {key:"customer_id", name:"거래처", width: 118 },
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118 },
    {key:"name", name:"품명", width: 118 },
    {key:"type", name:"품목 종류", width: 118 },
    {key:"unit", name:"단위", width: 118 },
    {key:"amount", name:"수주량", width: 118, editor: TextEditor},
    // {key:"route_operation_register", name:"지시 고유 번호", width: 118,},
    {key:"shipment_id", name:"납품 수량", width: 118, },
  ],
  deliveryRegister: [
    {key:"contract_id", name:"수주 번호", width: 118, formatter: SearchModalTest, type: 'order'},
    {key:"customer_id", name:"거래처", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"cm_id", name:"모델", width: 118, formatter: PlaceholderBox, placeholder: '자동입력' },
    {key:"product_id", name:"CODE", width: 118, formatter: SearchModalTest, type: 'product', staticCalendar: true, clearContract: true},
    {key:"name", name:"품명", width: 118 , formatter: PlaceholderBox, placeholder: '자동입력'  },
    {key:"type", name:"품목 종류", width: 118, formatter: PlaceholderBox, placeholder: '자동입력'   },
    {key:"unit", name:"단위", width: 118 , formatter: PlaceholderBox, placeholder: '자동입력'  },
    {key:"date", name:"납품 날짜", width: 118, formatter: CalendarBox   },
    {key:"lot_number", name:"LOT 선택", width: 118, formatter: LotDeliveryInfoModal, type: 'base'   },
    {key:"amount", name:"총 납품 수량", width: 118, placeholder: '0', type:"placeholder" },
  ],
  deliveryList: [
    {key:"identification", name:"납품 번호", width: 118},
    {key:"contract_id", name:"수주 번호", width: 118},
    {key:"customer_id", name:"거래처", width: 118 },
    {key:"cm_id", name:"모델", width: 118 },
    {key:"product_id", name:"CODE", width: 118,},
    {key:"name", name:"품명", width: 118   },
    {key:"type", name:"품목 종류", width: 118   },
    {key:"unit", name:"단위", width: 118   },
    {key:"date", name:"납품 날짜", width: 118   },
    {key:"amount", name:"총 납품 수량", width: 118   },
    {key:"lot_number", name:"LOT별 납품 수량", width: 118, formatter: LotDeliveryInfoModal, type: 'baseReadonly'   },
  ],
  deliveryModify: [
    {key:"identification", name:"수주 번호", width: 118, type: 'order'},
    {key:"customer_id", name:"거래처", width: 118 },
    {key:"cm_id", name:"모델", width: 118 },
    {key:"code", name:"CODE", width: 118, type: 'product' },
    {key:"name", name:"품명", width: 118   },
    {key:"type", name:"품목 종류", width: 118   },
    {key:"unit", name:"단위", width: 118   },
    {key:"date", name:"납품 날짜", width: 118, formatter:CalendarBox},
    {key:"lots", name:"LOT 선택", width: 118, formatter: LotDeliveryInfoModal, type: 'base'  },
    {key:"amount", name:"총 납품 수량", width: 118   },
  ],
  productChangeRegister: [
    {key: "customer_id", name: '거래처', formatter: PlaceholderBox, placeholder: '자동 입력', width: 168, type: 'autoInput'},
    {key: "cm_id", name: '모델',formatter: PlaceholderBox, placeholder: '자동 입력', width: 480, type: 'autoInput'},
    {key: "code", name: 'CODE',  formatter: SearchModalTest, type: 'product', width: 480},
    {key: "name", name:"품명", formatter: PlaceholderBox, placeholder: '자동입력',type: 'autoInput'},
  ],
  productChangeList: [
    {key: "customer_id", name: '거래처', width: 120},
    {key: "cm_id", name: '모델', width: 120},
    {key: "code", name: 'CODE', width: 208},
    {key: "material_name", name: '품명', width: 240},
    {key: 'type', name: '품목 종류', width: 120,  selectList: [
        {pk: '0', name: '반제품'},
        {pk: '1', name: '재공품'},
        {pk: '2', name: '완제품'},
      ]},
    {key: 'process_id', name: '생산 공정', width: 120},
    {key: 'title', name: '제목', width: 360},
    {key: 'register',name: '등록 날짜'},
    {key: 'writer', name: '작성자'}
  ],
  productChangeModify: [
    {key: "customer_id", name: '거래처', formatter: PlaceholderBox, placeholder: '자동 입력', width: 168, type: 'autoInput'},
    {key: "cm_id", name: '모델',formatter: PlaceholderBox, placeholder: '자동 입력', width: 480, type: 'autoInput'},
    {key: "code", name: 'CODE', formatter: SearchModalTest, type: 'product', width: 480},
    {key: "name", name:"품명", formatter: PlaceholderBox, placeholder: '자동입력',type: 'autoInput'},
  ],

  dailyInspectionMachine: [
    {key: "customer_id", name: '기계 제조사', formatter: PlaceholderBox, placeholder: '자동 입력', width: 168, type: 'autoInput'},
    {key: "cm_id", name: '기계 이름',formatter: PlaceholderBox, placeholder: '자동 입력', width: 480, type: 'autoInput'},
    {key: "code", name: '제조 번호', formatter: PlaceholderBox, width: 480, type: 'autoInput'},
    {key: "name", name:"기계 종류", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key: "name", name:"용접 종류", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key: "name", name:"제조 연원일", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
    {key: "name", name:"담당자", formatter: PlaceholderBox, placeholder: '자동입력', type: 'autoInput'},
  ],
  dailyInspectionMachinePicture: [
    {key: "machinePicture", name: '기계 사진', formatter: FileEditer,  width: 300, type: 'image'},
    {key: "photo1", name:'점검사항 부위01', formatter: FileEditer, type: 'image'},
    {key: "photo2", name:'점검사항 부위02', formatter: FileEditer, type: 'image'},
    {key: "photo3", name:"점검사항 부위03", formatter: FileEditer, type: 'image'},
    {key: "photo4", name:"점검사항 부위04", formatter: FileEditer, type: 'image'},
    {key: "photo5", name:"점검사항 부위05", formatter: FileEditer, type: 'image'},
    {key: "photo6", name:"점검사항 부위06", formatter: FileEditer, type: 'image'},
    {key: "photo7", name:"점검사항 부위07", formatter: FileEditer, type: 'image'},
    {key: "photo8", name:"점검사항 부위08", formatter: FileEditer, type: 'image'},
    {key: "photo9", name:"점검사항 부위09", formatter: FileEditer, type: 'image'},
  ],
  dailyInspectionMachineLegendary: [
    {key: "seq", name: '구분', formatter: PlaceholderBox, placeholder: '자동 입력', width: 48,},
    {key: "legendary", name: '범례',formatter: PlaceholderBox, editor: TextEditor, placeholder: '범례 입력',},
    {key: "content", name: '범례 설명',formatter: PlaceholderBox, editor: TextEditor, placeholder: '범례 설명 입력',},
  ],
  dailyInspectionMachineCheck: [
    {key: "sequence", name: '구분', formatter: PlaceholderBox, width: 48, type: 'autoInput'},
    {key: "title", name: '점검 항목',formatter: PlaceholderBox, editor: TextEditor, width: 500, placeholder: '점검 항목 입력',},
    {key: "standard", name: '점검 기준',formatter: PlaceholderBox, editor: TextEditor, width: 424, placeholder: '점검 기준 입력',},
    {key: "method", name: '점검 방법',formatter: PlaceholderBox, editor: TextEditor, width: 432, placeholder: '점검 방법 입력',},
    {key: "type", name: '기록 방록',formatter: DropDownEditor, placeholder: '자동 입력',
      selectList: [
        {pk: 0, name: "범례 적용"},
        {pk: 1, name: "수치 입력"},
      ]
    },
  ],
  dailyInspectionMachineETC: [
    {key: "etc", name: '기타 사항', formatter: PlaceholderBox, editor: TextEditor, placeholder: '기타 사항 입력'},
  ],
  dailyInspectionModal: [
    {key: "date", name: '점검 날짜', formatter: PlaceholderBox, editor: TextEditor, placeholder: '기타 사항 입력'},
    {key: "name", name: '기계 이름', formatter: PlaceholderBox, editor: TextEditor, placeholder: '기타 사항 입력'},
    {key: "code", name: '제조 번호', formatter: PlaceholderBox, editor: TextEditor, placeholder: '기타 사항 입력'},
    {key: "type", name: '기계 종류', formatter: PlaceholderBox, editor: TextEditor, placeholder: '기타 사항 입력'},
  ],
  test: [
    {key: 'userSearchModal', name: '유저 검색', formatter: SearchModalTest, type: 'user', width: 118,},
    {key: 'customerSearchModal', name: '거래처 검색', formatter: SearchModalTest, type: 'customer', width: 118,},
    {key: 'factorySearchModal', name: '공장 검색', formatter: SearchModalTest, type: 'factory', width: 118,},
    {key: 'segmentSearchModal', name: '공장 세분화 검색', formatter: SearchModalTest, type: 'segment', width: 118,},
    {key: 'modelSearchModal', name: '모델명 검색', formatter: SearchModalTest, type: 'model', width: 118,},
    {key: 'rawMaterialSearchModal', name: '원자재 검색', formatter: SearchModalTest, type: 'rawMaterial', width: 118,},
    {key: 'subMaterialSearchModal', name: '부자재 검색', formatter: SearchModalTest, type: 'subMaterial', width: 118,},
    {key: 'moldSearchModal', name: '금형 검색', formatter: SearchModalTest, type: 'mold', width: 118,},
    {key: 'machineSearchModal', name: '기계 검색', formatter: SearchModalTest, type: 'machine', width: 118,},
    {key: 'deviceSearchModal', name: '주변장치 검색', formatter: SearchModalTest, type: 'device', width: 118,},
    {key: 'productSearchModal', name: '제품 검색', formatter: SearchModalTest, type: 'product', width: 118,},
    {key: 'productSearchModal', name: '수주 검색', formatter: SearchModalTest, type: 'order', width: 118,},
    {key: 'FactoryInfoModal', name: '공장 정보', formatter: InfoModal, type: 'factoryRegister', summaryType: 'factory', width: 118,},
    {key: 'DeviceInfoModal', name: '주변장치 정보', formatter: InfoModal, type: 'deviceRegister', summaryType: 'device', width: 118,},
    {key: 'ProductInfoModal', name: '생산 품목 정보', formatter: InfoModal, type: 'productInfo', summaryType: 'mold', width: 118,},
    {key: 'BomInfoModal', name: 'BOM 등록', formatter: InfoModal, type: 'bomInfo', summaryType: 'product', width: 118,},
    {key: 'BomInfoReadonlyModal', name: '재고 확인', formatter: InfoModal, type: 'bomInfoReadOnly', summaryType: 'product', width: 118,},
    {key: 'MoldInfoModal', name: '금형 등록', formatter: InfoModal, type: 'moldInfo', summaryType: 'product_no_cavity', width: 118,},
    {key: 'MachineInfoModal', name: '기계 등록', formatter: InfoModal, type: 'machineInfo', summaryType: 'product_no_cavity', width: 118,},
  ]
}
